spring:
  application.name: eazy-recycling-service
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.qtnjbdjufwzbmdzndnku&password=VXU_kpk1qkm7mkb4djw
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jakarta.persistence:
        schema-generation.scripts:
          action: create
          create-target: create.sql
          create-source: metadata
          drop-target: drop.sql
          drop-source: metadata
      hibernate:
        hbm2ddl.auto: none
        show_sql: true
        format_sql: true
        schema-generation.scripts.action: create
        schema-generation.scripts.create-target: schema.sql
        dialect: org.hibernate.dialect.PostgreSQLDialect