alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: ers.eazysoftware.nl
    type: PRIMARY
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: ers
      match:
        authority:
          exact: ""
        path:
          prefix: /api
    - component:
        name: eazy-recycling-fe
      match:
        authority:
          exact: ""
        path:
          prefix: /
    - component:
        name: eazy-recycling-fe
        rewrite: /mobile.html
      match:
        authority:
          exact: ""
        path:
          prefix: /mobile
    - component:
        name: eazy-recycling-fe
        rewrite: /mobile.html
      match:
        authority:
          exact: ""
        path:
          prefix: /mobile/*
name: ers
region: ams
services:
  - http_port: 8080
    image:
      registry: colossus92
      # After submitting the spec, App Platform replaces the values in the spec with encrypted values. Once the values are encrypted, you can safely store the spec in the app’s repo.
      # https://docs.digitalocean.com/products/app-platform/how-to/deploy-from-container-images/#deploy-container-using-the-apps-spec
      registry_credentials: EV[1:PWh0bOoaZZ9yzzUZTNT7WfDQoVJ2ml5Y:d1BgPeXwL+yhvwFem0q80ok09ZVNd2Am/Y2i0ebFC7hWQUziYe/a6mKT5LdFFkuqu5y6Orqf0b2zx1WCtdmdyFRvOA==]
      registry_type: GHCR
      repository: eazy-recycling-service
      tag: main
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    name: ers
static_sites:
  - build_command: npm run build
    catchall_document: index.html
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: Colossus92/eazy-recycling-fe
    name: eazy-recycling-fe
    source_dir: /