services:
  backend-e2e:
    build:
      context: apps/springboot-backend
      dockerfile: Dockerfile
    command: ["java", "-jar", "app.jar", "--server.port=8081"]
    ports:
      - "8081:8081"
    env_file:
      - apps/springboot-backend/.env
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:54322/postgres?user=postgres&password=postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:5174
      - SUPABASE_API_URL=http://host.docker.internal:54321
      - SUPABASE_API_JWT_ISSUER=http://127.0.0.1:54321/auth/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - e2e-network

  frontend-e2e:
    build:
      context: apps/react-frontend
      dockerfile: Dockerfile.e2e
    ports:
      - "5174:80"
    depends_on:
      backend-e2e:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:8081
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge
