alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE
domains:
  - domain: ers.eazysoftware.nl
    type: PRIMARY
  - domain: app.eazyrecycling.nl
    type: ALIAS
envs:
  - key: VITE_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:ztuW71lsKt2A2EnExuVMj9/uYSy3c6/5:vNB7mEBobLhBeWRahQb6Cm0yRIehkYX8g+LFB+oNVQz5s1BOBkOh9QGwHUzHioc3m7WAU9S0jFA=]
  - key: VITE_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:kL1KaIRH9WLColCW16xXnuObJFUh2cDA:lmNIVoKV8ATFuNXMyBi5uMg8dtpvs9/1zQ6xIK2xnprYInjsLxbLddFfGeyoEZENdldZpTq5jL9zKe6+YJgvJKTVWu+d+IFjpKJcfV3D6MFd34BwrwO6ySSfrE/aAs5LGhQbAw4aVhhewlVABZhEicw6TIrRow7oOtkbI53XFDGPlv9sCHkAoqwfWAOb/L22i6BNkTszrmvyeFkasEaFWd9v/JLlISBRmRJMlncR3UmTdHrNrgOPs+0QNy/82RcO+oiyOFT8bugpaY+Q6Ip4/apJ2FyCibEIqFRU33qW5mA=]
  - key: VITE_API_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:D0IZTFnHR/cjqKgQJZHKC+2TUZS0pBhr:WOvAUSHuYORiB/2+Lx/dqVR72OaZsQ1FDcnOJ/36zIdz0Lv6GRJc6as7GXoZv2KhVou5MWBLpic=]
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: ers
      match:
        path:
          prefix: /api
    - component:
        name: react-frontend
      match:
        path:
          prefix: /
    - component:
        name: react-frontend
        rewrite: /mobile.html
      match:
        path:
          prefix: /mobile
    - component:
        name: react-frontend
        rewrite: /mobile.html
      match:
        path:
          prefix: /mobile/*
name: ers
region: ams
services:
  - envs:
      - key: SPRING_DATASOURCE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:zzvyGr9Od7stKtoTxIgv4Wm4/VxV3qLb:q2HSjT+2veCvwKJA8Xluxl6e0lpBd3K+QYF+gfIcw6GQ8untSc2cM9hFnZkhEIFakuT30QUUptG68pzng3813nIRv3A1gdG3/EoMUBoP/PP0JxPjlBNo3fKlhVa+KRFQOcbqhI3e0H8yvpiWkLUo2V0C9li/c0bsIrYyqnTo1iy0NmyQv5+OFrA8TOrAPxSUZYvyE7Oy]
      - key: SUPABASE_API_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:3AMLOqRMeYNc7TOJPrCrd9L4iTeCkrNC:hChxRrDJCFfpGqPBnOTpxMteL+bucXWZGkqOUdQan4yhjl7pveKJ2JFBCmjAkkMFTJYBjHNnXvg=]
      - key: SUPABASE_API_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:P+9jdZUkpTORSS9Iwpnx5+MYqWb8smce:WuevNUI3/0VogjiUOva3Dj1dfa7aQpKXc018hIKlCwG8FL6RdRczUVkZ07SBGipc7c94yha4gZFfnlXqs3IGxmLy5zwTp/r3rUpVqNL3JvqNnoHkJeig9qxLFzXgr+ZSJJFy1EFI6H7+IaHQ7K3nMEUhPAtPoLqDu9ITlLYfR4FNGweDKjbUSqbj7wTxQqvYd8m97Mc8+FMbsH+8QeUDeiLrg1q7B5zROZUe85o2Vz7vTmWZdKQu9XapnbdCk3k46R2UPhXo/pmjZV8LRntEMWsc7DLOfqr/XuPfuAcPRsF/RzHAq1jjW4P8xA==]
      - key: SUPABASE_API_PUBLISHABLE
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:OxzEx6a0Ihg1zTMawxMM1o5fWaLc6RRO:55rOq9ssAwyLTCkuBoA23GLcCt+vE/Noh7mD0GFUdK3SWmbsySCCgVhIeq3LAQZQFdXRDfLeMrt+rggrdQ79ThZ+xmsV1YV8x3Heow0vkoyeyOnujZmVb2y8qpBprYLOI5E8Y4RUuePJwakZMNFFSRotgiaO1KT/lcM/3PXtWft1OvDFge9itR6LmWdsiJGINU7+8rECe2terkaZb3zNkrduVGo9zlulWU+1mLJ7kcmTlU3QE+s0oH6Zkt27H7wHNBFL/1SGcKbVt2QOUXBDuaDF7ya7PuExqOOZ53bMaKQ=]
      - key: SUPABASE_API_JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:voTkuMo1CTVn+j7F+dQ9+WAqv7dZenV3:dcESB7mIINe8rZZE2pZKwA/48Ewsk6PtXQekX4+DlzJQPBXYefEeMrag/XoL5UJyI61lxZ/LQLhvCHAOx6m2ghYHupCWjkXaGAgxqDuqSVedbD5X92dF7Epu+TglX0EY3KOCsq12bwk=]
      - key: SUPABASE_API_JWT_ISSUER
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:waLtD+OdVWcbMu3eYYGwhpO4xiqH2v7H:QjrrNw1GVvHlVOlo5l4bv8KC/xkeOMONjYrfPxJf1898ZUhTtaI+hm+y9NBw/XDE9WfjETfz+SCRcQ+p0eZfEA==]
      - key: CLIENT_PFX_B64
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:8tLoZAjyZqLVcUQuLqSuLan4+O3cCTEw:VH1DhUhWx3D+kSO66PsvKI53kRQoPEsvKS+wfuj+cJZpFs8sOb1nnnlKd6E0gsU09OMnIbknH1nTbXKolWf+EwttmtYQPYKlyIkgjDG6pcbiaTmiSSCqsPv30PXjDMjUs7iFGeU6dYWkAAL4/ZhpgQLzWRnDN8LpSEZHGpLPHeUYXDSSG0objdgfEtfBLRpYMrp36b8qOhBSDXfCSoryQr5VhHqzzgyZUg1Dl5ERd/NnhxqkOO61sZZukTPeuEM2H7nYNLtevsXX9c9lT2Dnk8wpSQHTM+LCEbLBMewy2BhRrUUJsMcxhns6zeSyiuaBrxw7mKM0foMTyw5yCVdLhseYv665XiBh4VZqpqYpFpAflsrRv5UAdaMboCNo+fIooPyCGJwYt2x3TdkcnPiFiCOiJ51tvTzXDAGk3+MNf9FJXXtykSE72RXQW3SRKRT+koD/+N2a7X9i3HaJxAJuhMZC2Nzc2kUF6cTJgMcpl5ktFjkmnTB88+HhbPNjiEojzP6DLZzq8VJzrBqz/wq+DAqWw9PZgpJUtHT1M8vmK0jmzatDgdzMAp1cnI18XjGOig/aLpY5jdXe8mVM2nbTcQdx8Tmkh2jNwOZM8s1rpxUDdvbNE2QsQQOnKcy5BQc4SWzwR63OWhYKaTQTE+u9m3OEIODZyqBI9UzxP+EJmXY5gxRYMnB2BT72BEmkTm6BpDdO/VQu4gxkp8u5Qm3cENzZ40Jx8s8mqxQD297z58z9BGtMFZBwtrdFiy9hETBLhFDtArNaE0Omx0VjGJyJQYSjSkGgWHvNsphe1Inq4XJymEJmPpuqWC74pT1PPSRe1d2IAV4s+zCzcBhkXsbJmMDPmA42fMOBcdUG05IywpEU0aw0LqADhE4nrdUII2Vfu0s4Pr/q7NrnNuKKjEUX1YfK83qGACNQI+D9wjY/z/mhYci7pBZwmT1WB8FMVCe5+S2OpHdepEJlwKDO/qEahaG3EHCY2P3arezLj6kmv2SJ5mqx16oNgUvJow9bcBjW8A+vugUmxWARZyA87atj/Ui472UTtyBk0XPZIO7ZhMlwb6xsio5dIPNxlXqV71lZkgv38tJJa3UZkA0OlZiKFzu60E0mNSdMOCUpfUCZP5uDI+5d0yHv2WLQCyjfAi+trhHXBFLbu602+1HEfV669PBbxnVWBo6k6JNqax3yjK6kyXjcmlINCPcZbCwIYJWnLywkDyvXyI4+wwWIv6zOexuqalJnQMGmeztCG2LDwJrHmupg56iFpGS6+z9UJVKy4RvcMlbPeCFo0rODp5/vsi8JCkGG/qGn+qIoR+EihJd4s/ZT3Ea/iPKLXTrzpRwtQTW1eO5voBgMZU3dbZYSrKDAk3gd6i3FKsBHCqQQxHk7NkuWzgAdG2q3yNNlqePQH0geodAU7xIMlthcE4SmII1Khxpj0ASRdyrYpJMLa1TE0E329PRazILggmYrAQ8F3cBjlnuDXFpk70ydArI8sP6Jlyn6afNhcJlvUvSehLMQxRQq/fqRiHRlBjZ1h4WJXy20PL/9cjO0gyzGKmBDoYYzTyqxmsZ7ZgewwHPdUeR01VG+4UbnJaYfF+uF6NWAkkqPQQtEIhT563Eg23D+Fk+J6vRiyiYwms3UDA13K0MynhwKno3kTiPuLDxB05YvL/ds5CI4oEkL8b8rVWr7c9GFwcsBhwaO9gfwlx9HJ1J2DTqg6Gph6BbHaUDjl8ePDzbt3QHPKqLg0RbU1y8qjQEOI0WFrx5GHfquiKQZehF2s6lLC5vif+EY9znUM+FX1HBwSFP7gTAgzJdf+cNrP6otRQ9SFncKQOwI420pU9ruJDR/kQ3EIteDfETw/8lX4lRZXpFBNSZS30XvrusfOGPCIHT/l0zRsJdS/LXSryieXdovtZlUDNV9yHE1EieioKefXBGGIylijzkmyiwMkSwA+ZrFGfWqPGrmGM4KJmpSFNY1bpcEs+K0IIfX3V6CAavoSOsvk/FOMuIr6jQTo1WsukXgEf0wtC6Ju2tTO2jtMjb6G5rn/lq6J8HwJa6AVJT7htB8vC7c5LKa6iQlt2SjLVrwCNYGnu7NrX7DpNGY28CwybFfBG9ALXU2FtKhhggqc3Th8uWmV4mxClJHZg3rNiOXqf9mq+NN8fHtqFUSEq6R6ves/9HYkSHJq3wnz2URjqV5nTJRm5CmtVsbn+Ukew6QbiUYSuzB6gdwWvZhAwODh4AMHbcQKT1zOQ5I/kR7AnMOM0ZUh/6kmkc5mVNTqKn077eYWc+v9I18u0bKxhSD6K4cKHFZmDgG4nOt4xbBcsJRzbY9u15mv1poCqgR7kMY6EICuSX4SmSIWMKhGC3BUnuqG6sEIc6sAhHQVQ5YZ2ujmyQHwvvXvjC87I8I0q4lGmovnOpPk0jBsvvpYwM823YkyiFYUNSLPY4IEAfwWv07a3XYVHaPS6VXr1H9wefVbCWGgWyDvmSIBDKbhqgVqJqTYKWE9P+TF/OayOFYgNmUCgLVEWYP1oveL1qGa3pT88HN/b7UAtYo78OM/9XzXJufZ9eqxmiVomGc0AeWk2GM3ek4qoSxSk6fAnRDQVgM8beOlpP9fJ3jf53XSQeyK4d/YxCYuCtgs9VfGoL+lqYhvTrENnMyTczrg8HaFm17DOxzsfI2/W6wb7DnDCYGLjhZr0cmDtG+v5mWh+h1IkfNKAJbK7srjf3pn3Vcu2+zlFvNSw3YlaenyPceZPIJlwqhzGCsUWIt0MDpM6c3NScX3s9c2movoR2ZKOUvF0373M5oDSZqgumj4rpbRM1GwRt7w5oQTMYiUrWfrLIfnGHNYaExSwvpqIi+T+3rRT2SFofcdvOQj+wQTEFYLumzGz6yuP9rpxsEuo+0fpYT0S5DJMkM5F9am1QTIZheDI+Ei3WNLbKwvxHNvVf8yp+0Bu3Wyr7goSUeMA94xtjLhZprG4pXBaldDqGsv9HjrPyNWcubnUAdcb+UThn0kbJOp0zQ1bpbmgaXt3FNwmPHwcDASylQS8qsH2XwK9LKiYgWbJZx9s5BpImD3Hix+Hpu3qlH1YjHqmrtYVOnjh5GGUCDoFtuqUo6nmdh9iCeaVqNM1N+WlBa/5RC2qZ8jI/VIzjIlzmPGn2WEvmLPlKKsVZcjSjS81I8hgnwrIf335E/DeOypT+grB88FtGvhvGeTOlr7rOmkQ6/6k7cEr5lh4+/3PRvWm++HoBQpwjLNeKykhkyXz1dYZjqOUUZn++hRHWJztcM7b1LN25IGbC8FkasluMF25Xe0Lr+HJjV+AwryYKvdGIZwv9LPH9T9rl3rG6WXmSscgaBfR5XknY1PpWmhmtFyYxDB9K+SpxmlBGPft2cJLEFJJfRIejZ+Sy93+Ci9Eh4+Gb0SqC31u8K8LF1MKQ7jes9H8w1Y0/hu7Xs7/lTIsmXFMWVFrJ4gnTjPIW00gf4fXhgVwzUpYyut0BuXKiNwh/yj9Pb17o7+zuwOjLR0Xw5Nyn5AZLrCX84h43dYVvZCQI5g2tHG6ehe7S74pWqWrLhyE6Bb21URamOP0TYY1IDvduW1WvrZ6uc4GK/aydRQUyq1V+ArbZ2xgvXj/Nt5AHctnDPMi59L5GjEGFJyC2X0cdiRA6oI6cP8sThKW6gtQIF+5eBDHkI5+5HEyNMbADDLCsY5yOYP5MB4OOoPz6MygA6aPHJxAaU3S7FQgM+kNthLP2TVjIE3Pew/S7ocL4N0KmJ619U7bIpZN6xmzfPBq6xOoYFPU+FY1eI3szNaPCgZaHwyzy1YQaxkUhFehHOXzRozzmHSYMfXiorSipFVVg+ZE9Lmvc7aLiSZHsjNKyUgAIY7otBwpEDImgkiCO268buzkQ6YWyiQiEqaviNk+LRiSVas/LcGcRD3P0JQ20WDMxyeDy7Skcuwd0idccoPwLHx0uurYvpEc+klGoFMO3av+GHYVOO+IwrZk99yu/qqDOIb1fWnzQmk+d95/A+PE+uyLev0bPai3mWnydVv3Bfri6akugEBdzTI4D2GJsTJRU72qysZkjr7sgi3o9y06vqeT/i6UBPeKfybiJqFJSpyjuCqu4yVfG4UJ1LD2AIPBtvxJOJEiBUzh3z2I8SiP6Ffz6rvjDx+U+ZlVa35odoH6aBXrO0HacPn1yVkZddYxuhL5Jce/iibCmJpS5/yolWGbT8ewVewf05+V4NBKHnk2nqIHi39nnVSWfNMEdJ/5+BZtEypYSvlaLW220W6cbFvED9wR280CbrtW0nHAiJOH4TFKxgth2+/9vd38xr/BHqN68VTQ0bXJM4d9YgqWhuZhnw/6BF1m343pdfHmmmFPEbnKK2x5T+qEyL0JN85DMKZVQBfNkbEvNbby99D/4fuOJ8m3tl5iTU/rD3ycbsi3jzvb46c9oAxwQsdvCMae8fFk32JDRKSDf+4TV4gT6D2KPSSxS96F38qF7XwspFxcC1GlyzxL1A4+hnIYmJl3m8hVujeGkvs0YD6sVk+7uCrc9bb4/oBGq5g7YhbFAZuUXCtiNpNRoZFJVybHUYse4QQQ94x1NB+wmpp96wpGbXrx8JDCfN3Ybu37/fYOUtJSz6R/7H1xuZ2QTamBAmCRnX2iBUmwNQ2RVzKHNx7lOlMxk54hFFHi6L4jn/M6b4XC3WP0LW2mkdzu7Thlk/cFAZja1m3OA9cgJYN4fPwbxQIJjvP3B8IXqCbo8q/rJbQs6akQFq72mVAsj3Pl6YnywJ5brKcbOKU+n+U4Cx6JaVsDsqI4KJG/H+cy0oDoiUnrpY4T6onAHmE/oYNjePKaxqwQrAtbtDPbfq2HoAQwtrtbxP5XUfRJ7tw/kzbT6U2hwklVUMZH+a5TfFBbP0PVseAi7KvFh2Gc0I9qyQ7cKCEHTMakIH+UhkWiJNpMy7RZblr7I3V/JtoSE+CONYNuRcumMcZUAx1J+sleWaF2zkKViYFQgy3uxEdEcUrkPtYcQNsoh2OALSiKxIanZfDbn0/QXw0UmZyX+tF3IN6un2tDLz90es1B+SMVx/AsuvL6dvHN2EsLjFASlxf8pgwpp6Aa1fVccLjE68A9lzTYfBmOFgya93wVYXrBeG6MXAdS2mnEj0xFhRFKCW+0aFFxpyBaWuB+feSVnyeXYdJQdMA+tYf8tTElsZIbmfWlr4XLYN2sOjx0klg+4JTiIP/dtmXsAhWoyECPIDtyFl0XoTXVczlLmOB6WY5MH9yY5ZqGMbPwkolcCn6R5fAyZwblX1J04UGJ7YlLMLU9tA/UViLo1IVl/ZGPWoR+tJLAC4nBCtCvpDFDA2SKq+/t9UkQGKwXx0Dj0uVtB3BtvmJwKaPErhsJ7y1tA6]
      - key: AMICE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:cmCCRdTemtUdWCPAB/SkPBTlq5W9zjEL:UqC1/VD3dVY57DXoxkMeDNFPhSwUsY7UYmTOUJv92fQQASzW1GErm9qJe94NsSmR/4ato0Ep]
      - key: AMICE_USERNAME
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:M7CRj3B9xQmOYcKoNQHxTSACMkwYz3EB:Z8DhqG92lnsfyahLbjgd+iDUhx2SRHwshbbjqq/oYFOF0/CR]
      - key: AMICE_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:nF6KsAuYHZ8Xo+0z6tLy/U1D5XcQPns8:f51oTp8mpYuxsOdm+T4KxqY2++EoRxJRYw==]
      - key: AMICE_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: AMICE_CERTIFICATE_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: AMICE_CERTIFICATE_PATH
        scope: RUN_AND_BUILD_TIME
        value: file:/tmp/client.pfx
    health_check:
      failure_threshold: 20
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 1
    http_port: 8080
    image:
      registry: colossus92
      registry_credentials: EV[1:5G3jADfm9vTKcbRt8jENfDBZu0CjGxek:r6LusnSQcoo0Znh4mdEoPK0Bp0QNOkFXJizMGbDp3p7NdkjJN/xMLuC9Q7yXfxXNhASNUr1bG17T7Zu+VV02ePKtGw==]
      registry_type: GHCR
      repository: eazy-recycling
      tag: main
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    log_destinations:
      - logtail:
          token: 4WUPyLjj2Vd4xsLMxrdwSCNg
        name: Better Stack
    name: ers
static_sites:
  - build_command: npm install && npm run build
    catchall_document: index.html
    environment_slug: node-js
    github:
      branch: main
      repo: Colossus92/eazy-recycling
    name: react-frontend
    output_dir: ./dist
    source_dir: ./apps/react-frontend
