alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE
domains:
  - domain: ers.eazysoftware.nl
    type: PRIMARY
  - domain: app.eazyrecycling.nl
    type: ALIAS
envs:
  - key: VITE_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:ztuW71lsKt2A2EnExuVMj9/uYSy3c6/5:vNB7mEBobLhBeWRahQb6Cm0yRIehkYX8g+LFB+oNVQz5s1BOBkOh9QGwHUzHioc3m7WAU9S0jFA=]
  - key: VITE_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:kL1KaIRH9WLColCW16xXnuObJFUh2cDA:lmNIVoKV8ATFuNXMyBi5uMg8dtpvs9/1zQ6xIK2xnprYInjsLxbLddFfGeyoEZENdldZpTq5jL9zKe6+YJgvJKTVWu+d+IFjpKJcfV3D6MFd34BwrwO6ySSfrE/aAs5LGhQbAw4aVhhewlVABZhEicw6TIrRow7oOtkbI53XFDGPlv9sCHkAoqwfWAOb/L22i6BNkTszrmvyeFkasEaFWd9v/JLlISBRmRJMlncR3UmTdHrNrgOPs+0QNy/82RcO+oiyOFT8bugpaY+Q6Ip4/apJ2FyCibEIqFRU33qW5mA=]
  - key: VITE_API_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:D0IZTFnHR/cjqKgQJZHKC+2TUZS0pBhr:WOvAUSHuYORiB/2+Lx/dqVR72OaZsQ1FDcnOJ/36zIdz0Lv6GRJc6as7GXoZv2KhVou5MWBLpic=]
  - key: PRICING_APP_BASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:CwcyIweXIfyuKEfklBY2HgAuLLGTS1kj:yLNftWpzpYQGATS2X7QHige1OHjjkcGz+aYUrxQ2ndjLkRJUj2YJZDPe3xKZy2A=]
  - key: PRICING_APP_BEARER_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:PjQJWhY6BueNGkF0OStJecveQ+StDpm1:Wk1vnEXpgr5JOcYSB79VwC3XFIH32r4N4vYCDtBv7kbP1iSr7uOEYbzRPZvBBlE5thpvRZENpVEhz61Qu8tiMczk]
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: ers
      match:
        path:
          prefix: /api
    - component:
        name: react-frontend
      match:
        path:
          prefix: /
    - component:
        name: react-frontend
        rewrite: /mobile.html
      match:
        path:
          prefix: /mobile
    - component:
        name: react-frontend
        rewrite: /mobile.html
      match:
        path:
          prefix: /mobile/*
name: ers
region: ams
services:
  - alerts:
      - operator: GREATER_THAN
        rule: CPU_UTILIZATION
        value: 75
        window: FIVE_MINUTES
      - operator: GREATER_THAN
        rule: MEM_UTILIZATION
        value: 75
        window: FIVE_MINUTES
    envs:
      - key: SPRING_DATASOURCE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:zzvyGr9Od7stKtoTxIgv4Wm4/VxV3qLb:q2HSjT+2veCvwKJA8Xluxl6e0lpBd3K+QYF+gfIcw6GQ8untSc2cM9hFnZkhEIFakuT30QUUptG68pzng3813nIRv3A1gdG3/EoMUBoP/PP0JxPjlBNo3fKlhVa+KRFQOcbqhI3e0H8yvpiWkLUo2V0C9li/c0bsIrYyqnTo1iy0NmyQv5+OFrA8TOrAPxSUZYvyE7Oy]
      - key: SUPABASE_API_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:3AMLOqRMeYNc7TOJPrCrd9L4iTeCkrNC:hChxRrDJCFfpGqPBnOTpxMteL+bucXWZGkqOUdQan4yhjl7pveKJ2JFBCmjAkkMFTJYBjHNnXvg=]
      - key: SUPABASE_API_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:P+9jdZUkpTORSS9Iwpnx5+MYqWb8smce:WuevNUI3/0VogjiUOva3Dj1dfa7aQpKXc018hIKlCwG8FL6RdRczUVkZ07SBGipc7c94yha4gZFfnlXqs3IGxmLy5zwTp/r3rUpVqNL3JvqNnoHkJeig9qxLFzXgr+ZSJJFy1EFI6H7+IaHQ7K3nMEUhPAtPoLqDu9ITlLYfR4FNGweDKjbUSqbj7wTxQqvYd8m97Mc8+FMbsH+8QeUDeiLrg1q7B5zROZUe85o2Vz7vTmWZdKQu9XapnbdCk3k46R2UPhXo/pmjZV8LRntEMWsc7DLOfqr/XuPfuAcPRsF/RzHAq1jjW4P8xA==]
      - key: SUPABASE_API_PUBLISHABLE
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:OxzEx6a0Ihg1zTMawxMM1o5fWaLc6RRO:55rOq9ssAwyLTCkuBoA23GLcCt+vE/Noh7mD0GFUdK3SWmbsySCCgVhIeq3LAQZQFdXRDfLeMrt+rggrdQ79ThZ+xmsV1YV8x3Heow0vkoyeyOnujZmVb2y8qpBprYLOI5E8Y4RUuePJwakZMNFFSRotgiaO1KT/lcM/3PXtWft1OvDFge9itR6LmWdsiJGINU7+8rECe2terkaZb3zNkrduVGo9zlulWU+1mLJ7kcmTlU3QE+s0oH6Zkt27H7wHNBFL/1SGcKbVt2QOUXBDuaDF7ya7PuExqOOZ53bMaKQ=]
      - key: SUPABASE_API_JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:voTkuMo1CTVn+j7F+dQ9+WAqv7dZenV3:dcESB7mIINe8rZZE2pZKwA/48Ewsk6PtXQekX4+DlzJQPBXYefEeMrag/XoL5UJyI61lxZ/LQLhvCHAOx6m2ghYHupCWjkXaGAgxqDuqSVedbD5X92dF7Epu+TglX0EY3KOCsq12bwk=]
      - key: SUPABASE_API_JWT_ISSUER
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:waLtD+OdVWcbMu3eYYGwhpO4xiqH2v7H:QjrrNw1GVvHlVOlo5l4bv8KC/xkeOMONjYrfPxJf1898ZUhTtaI+hm+y9NBw/XDE9WfjETfz+SCRcQ+p0eZfEA==]
      - key: CLIENT_PFX_B64
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:jPu1SaKqToxjO74IyLhHiAJYmeSlRAv4:he88IeY1mRrWNTEIv57xxVd5s4qMsCZtU5pDMHBCjfQco3caScSXLntIVrOJsFaslplhabnlzoR6psmBgbgZvsDIeIWVtH9ZE5ffIhPT3BLGycaSmJXg1p++M+T1bogaiVhN0PTML/Ta1WgAcki+yv3sjW4xt8ZZDLHQdJuLq7yVWEnjlhTJ8PuZciUjiSNz5LHVAukTjagY4TsW2lMaj6TWr9tN2dQTKG9YtevLFqKiYcsZ5kgsxWLskpGfDforrKXXZ3kpvBZga5tGd/GBV5djUOI1dmA4Qj01hVx59OesPICVHSWLMZO2jRzkLxDLkkCBAWML+/sGo1qfgSMXxqq+BOLtHFkYTYSVSh46fElrD18K0F/7QFFrLzjbgx2q9vm9aXV0Zr7ZwMqI4EDSQ5MIWMQDhXBfMiENLXiN+/mhuKAh9pHL1se94v+1Hm3NdfCbFvrDLsVI/4cMEUwdECZku7a3Rhm/tr+V5R/Z/9Y+MmAzEr8AEy7qhXySTINzpqRy/8cMYAAtHwELH2Dn0w7rt7s1vcQ6OPoFgVCwNkfbQPpPF+T3c3/FkmEwqHsbbi5D2sQ8C8vikwaE/fQ56Snb/GuCQSIOzoUmTmLzUaGZ3cXNzDcXC2LoWpNsVfVdDpBQ+NFx+Md/gwjsBPiWEk9dwV8zDikq6lhRJ3umnvrU2DFm87s+BwjaHkvIYVNDy8atml1iDaPTMuouRELNaBiy1OlzqiQy4flUUSo3Ra+UH1fYzq7KASmlSAbrShBto1rLoXV9phOU365IYoIxEWTYAPZyxXlW//rhqOgkfJnQCTfUkVaV8LmiuZrCdKymarYlY7fOkDl45bsoWoQ38crsjLe3zepJyi2C0CtvVtPWcFSuFpNT8MMH+gfwKARXSihN690GhLVRCo/Jdf1AZ3Zsv8+e6dUmPrtHgajzfnD0pbx0Tf9LFKaJDZkR3iC3p7wTfc2iaSQc/L4Ch7/IhuDxQSXeZdzLIk8xyn4ZD4N6BPNvXqkHWeqUryj1K3h99Crg/GUvWBr87ty6OdN29Nk+CdhhgzSAc3qSQcm8iUkS6yx8Ur2IBnX/vw/k6nJcOplkzjzYteHWBr9iPqAldkfn3+dxWcSpfNxfxkb1Xqry4nFzfbXrwbAC48fG0KJr0x+gpeBs29TGkXVng8goEWAJev+lqpyDfHdOUtGnlCYPlF5NU3ooS/k3PJ8LiYG5Nb9mzgKRV91JlfG23nePy5BOMDM3zDaT0/A4ba5puMLEP9AZB/Mt6yjkYJiUqkWTnqIuoBG9zQHXxgkqD5U+vtKFl36DkEMyyI+T39aSRDaKJeAUnY0OoopDcdfuM80Wpmw2AMN8E3KCfUEAzZZTfZqSPuBlfKQ4S7lQZh4G4iSEiLmju3d9Q6MjHFmAj3+FSty3/Aec2GnA+NFN300gqdr5x1ETsFl1N4rgWkYfYp51ERt85GdZsPt8bdSL7lSNev7G0t+Ghq8pA2AHt8Vl+09R1vKkwJ8LfSEFen1uTiWt5d0pcaVhNk2015Y89+XmKuDkQh7IuCPWApXd+170q5iem0uP4Oclpj+LhLP5v+QRfDWCrlQjaD+pLa5ul/UR1wXxPkBl2XGLbqXJd60VFQT1Z8ICKePHHYsWzmNi9VwDvhp7FdS1ioq0aFfeY0gczb5+5WYv6PPphxqJX434DcZRg3HI3m6xFn9rJpzD/kBWn4gQmiQymT0vGEIrWBjXHQ9okckDjXOZ4g+A9dPXV/rGZ+m8bseJ4SPfdRiwY8+OhTwD0Yv49GrkunKjc5TCkVULfKPT4cgpOYL5gps2sGKf75+CP/OWvD/8jkF/ERPel1AKAAXF+3p8ur3FORFafU/sLNy/l2fR0yk2g2nf9YN3IbkkW0U/iZ1IpcAvvxtJ0H8iCSXVu9y+5l8WYq4CklAM06q98tWtceOk2rdd8B0SA71bUY4HzzKcsQFNbvs9QgMvZL81syX+xLHksDyNjFkGNMg2jteoYAw9d7EkpGBVvcHuyyAiWF6IiBurpbiO0tYnVcjhkmc0Dyvf082M4uYPLnQrV+hEc/EmlSlgV1LQka/aQnnUQTS0Zj2b2et4hJqOuKeov3murSUyCpwHZ/I0dlOmyLVdIZcFm1L2MihqawdTi1hXF2pCFUpbVypddTYNwXLKdvp3hNsF9V+NFqMZ2IaKG+1QKMhGFoJGC00RRuJj38Klj+JEeFFFuuiuqYnttHHsdtbLN2cC8gveB6mh6fQb6rMxQ3ngIW2AtuYY8hwk/6YcG+B8T90JSs+6eoKZFPF51VCCz07wgNpaq6vP+Ne7vES6k4TkfaETXRAT/UGF97nHenuzFH7GqkuRJGhAHiZVm8yYPc9wJXZEbIhHvb2JRD+mSp8YWCwKjCNZ841oxomZLbMns8bWirR/BBPOmsNycFhmigJOIU9ck6hCumjHyEKsBpcAuufnQLRtOWEayWItx5a1UvgAKRcwilgWwRMl1W5KzYhzmrIcbaJBH81nF0xDy8B78wr0WD1zbUCVXm1SPSSpBp+VHRsMFpSCwvsMlTAZNlGVvlxOQe+VbCIrWWKalgdRO0guc7Yvqi9Yh7liw8xKtcKVWQIFKU/EpAno+fTTn8+YrA892V95vAn8k4IgPO0nb8a5q+otC+rwf24T+GxxtX1EtbR/ExHcmq0nc383O97YlKWF5FfyDBXaFZTbxS8G9GXMfYTEbHFRQanbDNuWXAXJE+aa5OLuG+Sq6ZlUnShA+ocIcCSVgersRubo7O1iHsA/x9g71adTxJb/xsRVRj3YgiXv9U80C/Y4LDz1Hp0TR8QdWMXLB0cPxLlG1GdzffOPWvyHSU87E8YUjKY/fwMBNtUlP11k4WhELXzJwJwv5ltcdVyNyVsdWyTS2eNztA5iMDXrNw5KPL077HW730ocPbrxE3jFgc/pJr91dLX0kz3mP81Fo2LhIM18cAxiUym066wEMw95v0Db0KCRj+avUZUTMIB5c1gl6UIBvhtrWKjpIwbQ6l3w/1/065qIQdT4yg1pPDBII2E7dAC4HjtlKtytkZYd66ANSeUMKB2ZCJ0x3ucSwWz99Tq02jWWh8Ceah+OPK6DjndkfZyY2RElBH/wbAeC8Tw4cgx6GNZVnMGjzaGQoh5eBl/nUPw2sva/Ix+4C0LJ4MqiAATs2o5aehYK2ySsfAB68sK/uvoAlXwbwrD+A+h6xmaVD47WoUvuvDw7bD8LoZf5IBBUwFPl45E9JDwrhBe75cHWIQZD74QZQpf8uoxbJUbeXcMQjSOFIVCd0L9FrGgqP7ktdeImOVJwTYOAuAc94zoFL9rOZim5IoU6tsPBVLTx6h7T0SH2F8L6744r6NNbh4fYB7L36jvGxlKw7GYradkbodJHkMXoWyKHRceu3zBiSk++JbZcT77QbeejRuIkbfqUrWWDCKeuRX9ARpUVSGaHP8yhyTWH4YviM1qvjVytzs5TwCNj9PLvbsxmeRfHN666UB5QfQE3JTCGgnI2eJw1AeW1Nf5IUS+83Y4m7c3E6pxt3gCLM2UwzLQpUIsetQYMg06UsrGwnhdwjASJTNhROik1v4+QoIMzkbDq93W6mFh34JchVRDnCqC2bNqIDrCtRt9l8jQz4hJiuWM/NXNMvheG2wufZ70EakCzSp0o6kYlNfTdtEyJsGPtDkvXJCj0+KB7eb/Xl80L72nOM1hlwAfPaTKGZQTyyvHjQY8/WUCs97aAARjqjwQWj2kNBs/e6nh7g1Ge/IymVrWOIIhy1idRLrBS1QyKLkBEOCvrJlMos4IQKamuf4CuvAV0UCZvVGXYWy/CPcaIuG/AZOAJ/ue6RpkzTEyQZuCfpXMHJc36t/glyWIwNLIKoQx72tIpy3NNH15UEZHaHz4UcnZ4o+qio7K/rZmHtNweV0dezdcdyqLrRqDgb5TvzUNZdN0+YAdjnmpQy5zrrSTXsGLrWOsRHfSP56M9R5GFVu1zocxZXWcA1yHGIUyQlH/7tM06yfDyjztgJM5NmXxXKpKCclTg42osF3e4rlfqRjH7j7eL/zyFipyQjodZlLO+B7yR3ZoiXlJn+zkFw1I1Zv+s+8uL21yk3dYyaw0r48cbPtwN9GfPLsr6xoaS3sH7mUDIm7TqkmlZsWTzPcV81wsUYKKPNHjHjgPCNogbyuRI1ArT+OweofjCqFbGvc17qexcg98Sf3Q///VXl9gO8wjNgjameHrmZg2M/DbXsmZ6Z70nonXjyMQFNsfQEAA/NSewdIPXQdxKB3P8JQXGHnHPhtK22Mlr0fkD4WBN/Y+HJsOpZni0CLcfF/JbZVccRzJ0SWylpYr3MyP8uV29YCoO/xj8wU3nGjEPRHOz/0dTTSpSiM4YGQQztcE09aXWJm6YgyAhybt9x/7ChsSU/eBOYqPb3sR2NtgQsMPjMtvJ7uJuZTKzP9XTavpbHh1r4e2k8rJqs3Z/2I94avWesQLXt0GUZTjVQTw99cBak9ARxR9jXCxWWX3B8TX5Id/MLlBBi0S5fV4wpDsxLSmk7EuaBQMKgw5ERzAbdEP6e9mWZ32WKGXPw72u3opmHrKgChKOhxcsH3lUSgL2csdCSPqvi9lix/g9qaNQUhrDuZFeAsu3V3HbWY0LH53RRjrtwkT9niLZH263p41sNQa5WaOIBaObSZ6xG6mBqb2M/g7923FfjCpn9g8ZQgptOMDQrvilnIieG2Fuy5jHz7QwRH0UXicLkuDLg5tmgc2+eBrZ1l6sUDvByHbvjnM2W+KyRrjotPpXgogSc3jmdlCal/iGtqJWTA9rNfddLTYCardSdPrPAxpLkUoeLBfwF7iXnkqrGDqqfovsEv3G3N154dVNyKPmwHNq/N0kGT+ktMZiYPmtk3mHqXNDo7cxqrURuycRsjv5r4ebM6IvQ21zV5n0iOf2AWNkan+KkS/eY+DRo7ZDnSnnCEC7H5xdwSPvWqcBY516uB+yTlL8CEBS87rxLTP4SlcGqNE0dqXozY1/5jnuI95kMsMmFQ0aLmrbZejnYOc9MH5V433L0Y9BrCCbvgt8htxaC4ahsyyONicNetr4rG0OUWzyiCUGyOSIzmym35vhQyRcVpUgtEWRgCX/fQYNwNoY6l+EJpeA2QSU64VezP0uh/QjOITuPLh0EUTJz8utgvNZOGhfZt1uYmaD3DfFnlkLDW4M/8yKppU3uuROwNo3CvKwJGDLW8zVKUOkH4mspcFLRUIWpmjuIAeCodbG+fY2xqLm1xm8aiHSHRDfrp4dSZdcznAvPEeo03QL6KGIW+6z4XxhIGBs+MouzZJ968QlU0lLOOsHM57JzUe9U37H1Llv8E9drDZq]
      - key: AMICE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:cmCCRdTemtUdWCPAB/SkPBTlq5W9zjEL:UqC1/VD3dVY57DXoxkMeDNFPhSwUsY7UYmTOUJv92fQQASzW1GErm9qJe94NsSmR/4ato0Ep]
      - key: AMICE_USERNAME
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:M7CRj3B9xQmOYcKoNQHxTSACMkwYz3EB:Z8DhqG92lnsfyahLbjgd+iDUhx2SRHwshbbjqq/oYFOF0/CR]
      - key: AMICE_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:nF6KsAuYHZ8Xo+0z6tLy/U1D5XcQPns8:f51oTp8mpYuxsOdm+T4KxqY2++EoRxJRYw==]
      - key: AMICE_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: AMICE_CERTIFICATE_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: AMICE_CERTIFICATE_PATH
        scope: RUN_AND_BUILD_TIME
        value: file:/tmp/client.pfx
      - key: EXACT_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:aL2Wt+RGrKD0Fm1vkrokA0S4bjqiXUGX:DxlVyzFecliL1SIfsNrfKF2LC48CUdzxAOLiTrlJDu8fCPf0+FqubYntRcwo0SrUiUKMWw==]
      - key: EXACT_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:OBdQsK3yRTadcc57j2t+Gc4WRTO9Fzh2:fFzDoTjTthlxy7m7ra4GIn4ScKkN78Qb2RZARQ==]
      - key: EXACT_REDIRECT_URI
        scope: RUN_AND_BUILD_TIME
        value: https://app.eazyrecycling.nl/api/admin/exact/callback
      - key: FRONTEND_URL
        scope: RUN_AND_BUILD_TIME
        value: https://app.eazyrecycling.nl
      - key: BETTERSTACK_SOURCE_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:V8wmhmd+jDEmWcX4z+zi+sgEtzPP5iMF:mYcjPQfs9kn6kHfetOPKNqXaXe3o2ThgRJm2QEdqR8ktHjvezNqIww==]
      - key: BETTERSTACK_INGESTING_HOST
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:ySM45tAfut5iCtoPE69QUjGtvqhi/ejG:sI47yi7Q64C7FAZOXcsZMgcl375OBPjjYkbT0OEmgy6vSVcQWT2WCFqLdGxsnAXEg9oZXVk=]
    health_check:
      failure_threshold: 20
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 1
    http_port: 8080
    image:
      registry: colossus92
      registry_credentials: EV[1:5G3jADfm9vTKcbRt8jENfDBZu0CjGxek:r6LusnSQcoo0Znh4mdEoPK0Bp0QNOkFXJizMGbDp3p7NdkjJN/xMLuC9Q7yXfxXNhASNUr1bG17T7Zu+VV02ePKtGw==]
      registry_type: GHCR
      repository: eazy-recycling
      tag: main
    instance_count: 1
    instance_size_slug: apps-d-1vcpu-2gb
    name: ers
static_sites:
  - build_command: npm install && npm run build
    catchall_document: index.html
    environment_slug: node-js
    github:
      branch: main
      repo: Colossus92/eazy-recycling
    name: react-frontend
    output_dir: ./dist
    source_dir: ./apps/react-frontend
