/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressDto
 */
export interface AddressDto {
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'streetName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'buildingName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'buildingNumber': string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'postalCode': string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'country'?: string;
}

