/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressRequest
 */
export interface AddressRequest {
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'streetName': string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'buildingName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'buildingNumber': string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'postalCode': string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'country': string;
}

