/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApplicationContextClassLoader } from './application-context-class-loader';
// May contain unused imports in some cases
// @ts-ignore
import type { Environment } from './environment';

/**
 * 
 * @export
 * @interface ApplicationContext
 */
export interface ApplicationContext {
    /**
     * 
     * @type {any}
     * @memberof ApplicationContext
     */
    'autowireCapableBeanFactory'?: any;
    /**
     * 
     * @type {number}
     * @memberof ApplicationContext
     */
    'startupDate'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationContext
     */
    'applicationName'?: string;
    /**
     * 
     * @type {any}
     * @memberof ApplicationContext
     */
    'parent'?: any;
    /**
     * 
     * @type {string}
     * @memberof ApplicationContext
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationContext
     */
    'displayName'?: string;
    /**
     * 
     * @type {Environment}
     * @memberof ApplicationContext
     */
    'environment'?: Environment;
    /**
     * 
     * @type {number}
     * @memberof ApplicationContext
     */
    'beanDefinitionCount'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationContext
     */
    'beanDefinitionNames'?: Array<string>;
    /**
     * 
     * @type {any}
     * @memberof ApplicationContext
     */
    'parentBeanFactory'?: any;
    /**
     * 
     * @type {ApplicationContextClassLoader}
     * @memberof ApplicationContext
     */
    'classLoader'?: ApplicationContextClassLoader;
}

