/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogItemCategoryDto
 */
export interface CatalogItemCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCategoryDto
     */
    'updatedBy'?: string;
}

