/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CatalogItemCategoryDto } from './catalog-item-category-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanyDto } from './company-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { VatRateDto } from './vat-rate-dto';

/**
 * 
 * @export
 * @interface CatalogItemDto
 */
export interface CatalogItemDto {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'type': CatalogItemDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'unitOfMeasure': string;
    /**
     * 
     * @type {VatRateDto}
     * @memberof CatalogItemDto
     */
    'vatRate': VatRateDto;
    /**
     * 
     * @type {CatalogItemCategoryDto}
     * @memberof CatalogItemDto
     */
    'category'?: CatalogItemCategoryDto;
    /**
     * 
     * @type {CompanyDto}
     * @memberof CatalogItemDto
     */
    'consignorParty'?: CompanyDto;
    /**
     * 
     * @type {number}
     * @memberof CatalogItemDto
     */
    'defaultPrice'?: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'purchaseAccountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'salesAccountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'updatedBy'?: string;
}

export const CatalogItemDtoTypeEnum = {
    Material: 'MATERIAL',
    Product: 'PRODUCT',
    WasteStream: 'WASTE_STREAM'
} as const;

export type CatalogItemDtoTypeEnum = typeof CatalogItemDtoTypeEnum[keyof typeof CatalogItemDtoTypeEnum];


