/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressRequest } from './address-request';

/**
 * 
 * @export
 * @interface CompanyRequest
 */
export interface CompanyRequest {
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    'chamberOfCommerceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    'vihbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    'name': string;
    /**
     * 
     * @type {AddressRequest}
     * @memberof CompanyRequest
     */
    'address'?: AddressRequest;
}

