/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressView } from './address-view';

/**
 * 
 * @export
 * @interface ContainerLocationView
 */
export interface ContainerLocationView {
    /**
     * 
     * @type {string}
     * @memberof ContainerLocationView
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerLocationView
     */
    'companyName'?: string;
    /**
     * 
     * @type {AddressView}
     * @memberof ContainerLocationView
     */
    'addressView'?: AddressView;
}

