/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimingConstraintRequest } from './timing-constraint-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WeightTicketRequestPickupLocation } from './weight-ticket-request-pickup-location';

/**
 * 
 * @export
 * @interface ContainerTransportRequest
 */
export interface ContainerTransportRequest {
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'consignorPartyId': string;
    /**
     * 
     * @type {TimingConstraintRequest}
     * @memberof ContainerTransportRequest
     */
    'pickup': TimingConstraintRequest;
    /**
     * 
     * @type {TimingConstraintRequest}
     * @memberof ContainerTransportRequest
     */
    'delivery'?: TimingConstraintRequest;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'transportType': ContainerTransportRequestTransportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'containerOperation': ContainerTransportRequestContainerOperationEnum;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'driverId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'carrierPartyId': string;
    /**
     * 
     * @type {WeightTicketRequestPickupLocation}
     * @memberof ContainerTransportRequest
     */
    'pickupLocation': WeightTicketRequestPickupLocation;
    /**
     * 
     * @type {WeightTicketRequestPickupLocation}
     * @memberof ContainerTransportRequest
     */
    'deliveryLocation': WeightTicketRequestPickupLocation;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'truckId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'containerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerTransportRequest
     */
    'note': string;
}

export const ContainerTransportRequestTransportTypeEnum = {
    Container: 'CONTAINER',
    Waste: 'WASTE'
} as const;

export type ContainerTransportRequestTransportTypeEnum = typeof ContainerTransportRequestTransportTypeEnum[keyof typeof ContainerTransportRequestTransportTypeEnum];
export const ContainerTransportRequestContainerOperationEnum = {
    Exchange: 'EXCHANGE',
    Pickup: 'PICKUP',
    Empty: 'EMPTY',
    Delivery: 'DELIVERY'
} as const;

export type ContainerTransportRequestContainerOperationEnum = typeof ContainerTransportRequestContainerOperationEnum[keyof typeof ContainerTransportRequestContainerOperationEnum];


