/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressRequest } from './address-request';
// May contain unused imports in some cases
// @ts-ignore
import type { GoodsRequest } from './goods-request';

/**
 * 
 * @export
 * @interface CreateWeightTicketRequest
 */
export interface CreateWeightTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'carrierParty': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'consignorParty': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'consigneeParty': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'pickupParty': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'truckId': string;
    /**
     * 
     * @type {Array<GoodsRequest>}
     * @memberof CreateWeightTicketRequest
     */
    'goods': Array<GoodsRequest>;
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'reclamation': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeightTicketRequest
     */
    'note'?: string;
    /**
     * 
     * @type {AddressRequest}
     * @memberof CreateWeightTicketRequest
     */
    'loadingAddress': AddressRequest;
    /**
     * 
     * @type {AddressRequest}
     * @memberof CreateWeightTicketRequest
     */
    'unloadingAddress': AddressRequest;
}

