/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WasteStreamDetailViewPickupLocation } from './waste-stream-detail-view-pickup-location';

/**
 * 
 * @export
 * @interface DriverPlanningItem
 */
export interface DriverPlanningItem {
    /**
     * 
     * @type {string}
     * @memberof DriverPlanningItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DriverPlanningItem
     */
    'displayNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof DriverPlanningItem
     */
    'pickupDateTime': string;
    /**
     * 
     * @type {string}
     * @memberof DriverPlanningItem
     */
    'deliveryDateTime'?: string;
    /**
     * 
     * @type {WasteStreamDetailViewPickupLocation}
     * @memberof DriverPlanningItem
     */
    'pickupLocation': WasteStreamDetailViewPickupLocation;
    /**
     * 
     * @type {WasteStreamDetailViewPickupLocation}
     * @memberof DriverPlanningItem
     */
    'deliveryLocation': WasteStreamDetailViewPickupLocation;
    /**
     * 
     * @type {string}
     * @memberof DriverPlanningItem
     */
    'containerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DriverPlanningItem
     */
    'status': DriverPlanningItemStatusEnum;
}

export const DriverPlanningItemStatusEnum = {
    Unplanned: 'UNPLANNED',
    Planned: 'PLANNED',
    Finished: 'FINISHED',
    Invoiced: 'INVOICED'
} as const;

export type DriverPlanningItemStatusEnum = typeof DriverPlanningItemStatusEnum[keyof typeof DriverPlanningItemStatusEnum];


