/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterRegistration
 */
export interface FilterRegistration {
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterRegistration
     */
    'servletNameMappings'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterRegistration
     */
    'urlPatternMappings'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FilterRegistration
     */
    'initParameters'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof FilterRegistration
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FilterRegistration
     */
    'className'?: string;
}

