/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GoodsRequest
 */
export interface GoodsRequest {
    /**
     * 
     * @type {string}
     * @memberof GoodsRequest
     */
    'wasteStreamNumber': string;
    /**
     * 
     * @type {number}
     * @memberof GoodsRequest
     */
    'netWeight': number;
    /**
     * 
     * @type {string}
     * @memberof GoodsRequest
     */
    'unit': string;
}

