/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyDto } from './company-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { GoodsItemDto } from './goods-item-dto';

/**
 * 
 * @export
 * @interface GoodsDto
 */
export interface GoodsDto {
    /**
     * 
     * @type {string}
     * @memberof GoodsDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof GoodsDto
     */
    'uuid'?: string;
    /**
     * 
     * @type {GoodsItemDto}
     * @memberof GoodsDto
     */
    'goodsItem': GoodsItemDto;
    /**
     * 
     * @type {number}
     * @memberof GoodsDto
     */
    'consignorClassification': number;
    /**
     * 
     * @type {CompanyDto}
     * @memberof GoodsDto
     */
    'consigneeParty': CompanyDto;
    /**
     * 
     * @type {CompanyDto}
     * @memberof GoodsDto
     */
    'pickupParty': CompanyDto;
    /**
     * 
     * @type {string}
     * @memberof GoodsDto
     */
    'updatedAt'?: string;
}

