/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GoodsItemDto
 */
export interface GoodsItemDto {
    /**
     * 
     * @type {number}
     * @memberof GoodsItemDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GoodsItemDto
     */
    'wasteStreamNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof GoodsItemDto
     */
    'netNetWeight': number;
    /**
     * 
     * @type {string}
     * @memberof GoodsItemDto
     */
    'unit': string;
    /**
     * 
     * @type {number}
     * @memberof GoodsItemDto
     */
    'quantity': number;
    /**
     * 
     * @type {string}
     * @memberof GoodsItemDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GoodsItemDto
     */
    'euralCode': string;
    /**
     * 
     * @type {string}
     * @memberof GoodsItemDto
     */
    'processingMethodCode': string;
}

