/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InvoiceView
 */
export interface InvoiceView {
    /**
     * 
     * @type {number}
     * @memberof InvoiceView
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'invoiceNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'invoiceType': string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'documentType': string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'invoiceDate': string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'customerName': string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceView
     */
    'customerNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof InvoiceView
     */
    'totalExclVat': number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceView
     */
    'totalInclVat': number;
}

