/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VatBreakdownLineView } from './vat-breakdown-line-view';

/**
 * 
 * @export
 * @interface InvoiceTotalsView
 */
export interface InvoiceTotalsView {
    /**
     * 
     * @type {number}
     * @memberof InvoiceTotalsView
     */
    'totalExclVat': number;
    /**
     * 
     * @type {Array<VatBreakdownLineView>}
     * @memberof InvoiceTotalsView
     */
    'vatBreakdown': Array<VatBreakdownLineView>;
    /**
     * 
     * @type {number}
     * @memberof InvoiceTotalsView
     */
    'totalVat': number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceTotalsView
     */
    'totalInclVat': number;
}

