/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JspPropertyGroupDescriptor } from './jsp-property-group-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { TaglibDescriptor } from './taglib-descriptor';

/**
 * 
 * @export
 * @interface JspConfigDescriptor
 */
export interface JspConfigDescriptor {
    /**
     * 
     * @type {Array<TaglibDescriptor>}
     * @memberof JspConfigDescriptor
     */
    'taglibs'?: Array<TaglibDescriptor>;
    /**
     * 
     * @type {Array<JspPropertyGroupDescriptor>}
     * @memberof JspConfigDescriptor
     */
    'jspPropertyGroups'?: Array<JspPropertyGroupDescriptor>;
}

