/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MaterialToSyncResponse
 */
export interface MaterialToSyncResponse {
    /**
     * 
     * @type {string}
     * @memberof MaterialToSyncResponse
     */
    'materialId': string;
    /**
     * 
     * @type {string}
     * @memberof MaterialToSyncResponse
     */
    'materialName': string;
    /**
     * 
     * @type {number}
     * @memberof MaterialToSyncResponse
     */
    'currentPrice': number;
    /**
     * 
     * @type {number}
     * @memberof MaterialToSyncResponse
     */
    'lastSyncedPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof MaterialToSyncResponse
     */
    'externalProductId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MaterialToSyncResponse
     */
    'priceStatus': number;
    /**
     * 
     * @type {string}
     * @memberof MaterialToSyncResponse
     */
    'priceStatusLabel': string;
}

