/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MaterialPriceResponse
 */
export interface MaterialPriceResponse {
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'materialGroupId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'materialGroupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'unitOfMeasure': string;
    /**
     * 
     * @type {number}
     * @memberof MaterialPriceResponse
     */
    'defaultPrice'?: number;
}

