/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MaterialPriceResponse
 */
export interface MaterialPriceResponse {
    /**
     * 
     * @type {number}
     * @memberof MaterialPriceResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof MaterialPriceResponse
     */
    'materialId': number;
    /**
     * 
     * @type {number}
     * @memberof MaterialPriceResponse
     */
    'price': number;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'currency': string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'validFrom': string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'validTo'?: string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'createdByName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MaterialPriceResponse
     */
    'updatedByName'?: string;
}

