/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompleteCompanyView } from './complete-company-view';

/**
 * 
 * @export
 * @interface PagedCompanyResponse
 */
export interface PagedCompanyResponse {
    /**
     * 
     * @type {Array<CompleteCompanyView>}
     * @memberof PagedCompanyResponse
     */
    'content': Array<CompleteCompanyView>;
    /**
     * 
     * @type {number}
     * @memberof PagedCompanyResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof PagedCompanyResponse
     */
    'size': number;
    /**
     * 
     * @type {number}
     * @memberof PagedCompanyResponse
     */
    'totalElements': number;
    /**
     * 
     * @type {number}
     * @memberof PagedCompanyResponse
     */
    'totalPages': number;
}

