/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlanningTransportView } from './planning-transport-view';

/**
 * 
 * @export
 * @interface PlanningTransportsView
 */
export interface PlanningTransportsView {
    /**
     * 
     * @type {string}
     * @memberof PlanningTransportsView
     */
    'truck': string;
    /**
     * 
     * @type {{ [key: string]: Array<PlanningTransportView>; }}
     * @memberof PlanningTransportsView
     */
    'transports': { [key: string]: Array<PlanningTransportView>; };
}

