/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConsignorPartyRequest } from './consignor-party-request';
// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryLocationRequest } from './delivery-location-request';
// May contain unused imports in some cases
// @ts-ignore
import type { ReceivalDeclarationRequestPickupLocation } from './receival-declaration-request-pickup-location';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteTypeRequest } from './waste-type-request';

/**
 * 
 * @export
 * @interface ReceivalDeclarationRequest
 */
export interface ReceivalDeclarationRequest {
    /**
     * 
     * @type {string}
     * @memberof ReceivalDeclarationRequest
     */
    'wasteStreamNumber': string;
    /**
     * 
     * @type {WasteTypeRequest}
     * @memberof ReceivalDeclarationRequest
     */
    'wasteType': WasteTypeRequest;
    /**
     * 
     * @type {string}
     * @memberof ReceivalDeclarationRequest
     */
    'collectionType': string;
    /**
     * 
     * @type {ReceivalDeclarationRequestPickupLocation}
     * @memberof ReceivalDeclarationRequest
     */
    'pickupLocation'?: ReceivalDeclarationRequestPickupLocation;
    /**
     * 
     * @type {DeliveryLocationRequest}
     * @memberof ReceivalDeclarationRequest
     */
    'deliveryLocation': DeliveryLocationRequest;
    /**
     * 
     * @type {ConsignorPartyRequest}
     * @memberof ReceivalDeclarationRequest
     */
    'consignorParty': ConsignorPartyRequest;
    /**
     * 
     * @type {number}
     * @memberof ReceivalDeclarationRequest
     */
    'consignorClassification': number;
    /**
     * 
     * @type {string}
     * @memberof ReceivalDeclarationRequest
     */
    'pickupParty': string;
    /**
     * 
     * @type {string}
     * @memberof ReceivalDeclarationRequest
     */
    'dealerParty'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceivalDeclarationRequest
     */
    'collectorParty'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceivalDeclarationRequest
     */
    'brokerParty'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReceivalDeclarationRequest
     */
    'transporterIds': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ReceivalDeclarationRequest
     */
    'totalWeight': number;
    /**
     * 
     * @type {number}
     * @memberof ReceivalDeclarationRequest
     */
    'totalShipments': number;
    /**
     * 
     * @type {number}
     * @memberof ReceivalDeclarationRequest
     */
    'year': number;
    /**
     * 
     * @type {number}
     * @memberof ReceivalDeclarationRequest
     */
    'month': number;
}

