/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApplicationContext } from './application-context';
// May contain unused imports in some cases
// @ts-ignore
import type { RedirectViewStatusCode } from './redirect-view-status-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ServletContext } from './servlet-context';

/**
 * 
 * @export
 * @interface RedirectView
 */
export interface RedirectView {
    /**
     * 
     * @type {ApplicationContext}
     * @memberof RedirectView
     */
    'applicationContext'?: ApplicationContext;
    /**
     * 
     * @type {ServletContext}
     * @memberof RedirectView
     */
    'servletContext'?: ServletContext;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    'contentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    'requestContextAttribute'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RedirectView
     */
    'staticAttributes'?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'exposePathVariables'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'exposeContextBeansAsAttributes'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RedirectView
     */
    'exposedContextBeanNames'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    'beanName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    'url'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'contextRelative'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'http10Compatible'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'exposeModelAttributes'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    'encodingScheme'?: string;
    /**
     * 
     * @type {RedirectViewStatusCode}
     * @memberof RedirectView
     */
    'statusCode'?: RedirectViewStatusCode;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'expandUriTemplateVariables'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'propagateQueryParams'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RedirectView
     */
    'hosts'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'redirectView'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    'propagateQueryProperties'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RedirectView
     */
    'attributesMap'?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RedirectView
     */
    'attributes'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    'attributesCSV'?: string;
}

