/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncFromExactResponse
 */
export interface SyncFromExactResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SyncFromExactResponse
     */
    'success': boolean;
    /**
     * 
     * @type {string}
     * @memberof SyncFromExactResponse
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'recordsSynced': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'recordsCreated': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'recordsUpdated': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'recordsConflicted': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'recordsPendingReview': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'deletedRecordsProcessed': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'deletedRecordsDeleted': number;
    /**
     * 
     * @type {number}
     * @memberof SyncFromExactResponse
     */
    'deletedRecordsNotFound': number;
}

