/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncJobsEnqueuedResponse
 */
export interface SyncJobsEnqueuedResponse {
    /**
     * 
     * @type {number}
     * @memberof SyncJobsEnqueuedResponse
     */
    'createJobsEnqueued': number;
    /**
     * 
     * @type {number}
     * @memberof SyncJobsEnqueuedResponse
     */
    'updateJobsEnqueued': number;
    /**
     * 
     * @type {number}
     * @memberof SyncJobsEnqueuedResponse
     */
    'deleteJobsEnqueued': number;
    /**
     * 
     * @type {number}
     * @memberof SyncJobsEnqueuedResponse
     */
    'totalJobsEnqueued': number;
}

