/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransportReorderRequest
 */
export interface TransportReorderRequest {
    /**
     * 
     * @type {string}
     * @memberof TransportReorderRequest
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof TransportReorderRequest
     */
    'licensePlate': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransportReorderRequest
     */
    'transportIds': Array<string>;
}

