/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyBranchDto } from './company-branch-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanyDto } from './company-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { GoodsDto } from './goods-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileDto } from './profile-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Truck } from './truck';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteContainerDto } from './waste-container-dto';

/**
 * 
 * @export
 * @interface TransportDto
 */
export interface TransportDto {
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'displayNumber'?: string;
    /**
     * 
     * @type {CompanyDto}
     * @memberof TransportDto
     */
    'consignorParty': CompanyDto;
    /**
     * 
     * @type {CompanyDto}
     * @memberof TransportDto
     */
    'carrierParty': CompanyDto;
    /**
     * 
     * @type {CompanyDto}
     * @memberof TransportDto
     */
    'pickupCompany'?: CompanyDto;
    /**
     * 
     * @type {CompanyBranchDto}
     * @memberof TransportDto
     */
    'pickupCompanyBranch'?: CompanyBranchDto;
    /**
     * 
     * @type {LocationDto}
     * @memberof TransportDto
     */
    'pickupLocation': LocationDto;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'pickupDateTime': string;
    /**
     * 
     * @type {CompanyDto}
     * @memberof TransportDto
     */
    'deliveryCompany'?: CompanyDto;
    /**
     * 
     * @type {CompanyBranchDto}
     * @memberof TransportDto
     */
    'deliveryCompanyBranch'?: CompanyBranchDto;
    /**
     * 
     * @type {LocationDto}
     * @memberof TransportDto
     */
    'deliveryLocation': LocationDto;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'deliveryDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'transportType': TransportDtoTransportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'containerOperation'?: TransportDtoContainerOperationEnum;
    /**
     * 
     * @type {WasteContainerDto}
     * @memberof TransportDto
     */
    'wasteContainer'?: WasteContainerDto;
    /**
     * 
     * @type {Truck}
     * @memberof TransportDto
     */
    'truck'?: Truck;
    /**
     * 
     * @type {ProfileDto}
     * @memberof TransportDto
     */
    'driver'?: ProfileDto;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'note': string;
    /**
     * 
     * @type {GoodsDto}
     * @memberof TransportDto
     */
    'goods'?: GoodsDto;
    /**
     * 
     * @type {number}
     * @memberof TransportDto
     */
    'transportHours'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransportDto
     */
    'sequenceNumber': number;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    'status': TransportDtoStatusEnum;
}

export const TransportDtoTransportTypeEnum = {
    Container: 'CONTAINER',
    Waste: 'WASTE'
} as const;

export type TransportDtoTransportTypeEnum = typeof TransportDtoTransportTypeEnum[keyof typeof TransportDtoTransportTypeEnum];
export const TransportDtoContainerOperationEnum = {
    Exchange: 'EXCHANGE',
    Pickup: 'PICKUP',
    Empty: 'EMPTY',
    Delivery: 'DELIVERY'
} as const;

export type TransportDtoContainerOperationEnum = typeof TransportDtoContainerOperationEnum[keyof typeof TransportDtoContainerOperationEnum];
export const TransportDtoStatusEnum = {
    Unplanned: 'UNPLANNED',
    Planned: 'PLANNED',
    Finished: 'FINISHED',
    Invoiced: 'INVOICED'
} as const;

export type TransportDtoStatusEnum = typeof TransportDtoStatusEnum[keyof typeof TransportDtoStatusEnum];


