/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransportView } from './transport-view';

/**
 * 
 * @export
 * @interface TransportsView
 */
export interface TransportsView {
    /**
     * 
     * @type {string}
     * @memberof TransportsView
     */
    'truck': string;
    /**
     * 
     * @type {{ [key: string]: Array<TransportView>; }}
     * @memberof TransportsView
     */
    'transports': { [key: string]: Array<TransportView>; };
}

