/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyView } from './company-view';
// May contain unused imports in some cases
// @ts-ignore
import type { DriverView } from './driver-view';
// May contain unused imports in some cases
// @ts-ignore
import type { Instant } from './instant';
// May contain unused imports in some cases
// @ts-ignore
import type { TruckView } from './truck-view';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteContainerView } from './waste-container-view';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteStreamDetailViewPickupLocation } from './waste-stream-detail-view-pickup-location';

/**
 * 
 * @export
 * @interface TransportDetailView
 */
export interface TransportDetailView {
    /**
     * 
     * @type {string}
     * @memberof TransportDetailView
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TransportDetailView
     */
    'displayNumber'?: string;
    /**
     * 
     * @type {CompanyView}
     * @memberof TransportDetailView
     */
    'consignorParty': CompanyView;
    /**
     * 
     * @type {CompanyView}
     * @memberof TransportDetailView
     */
    'carrierParty': CompanyView;
    /**
     * 
     * @type {WasteStreamDetailViewPickupLocation}
     * @memberof TransportDetailView
     */
    'pickupLocation': WasteStreamDetailViewPickupLocation;
    /**
     * 
     * @type {Instant}
     * @memberof TransportDetailView
     */
    'pickupDateTime': Instant;
    /**
     * 
     * @type {WasteStreamDetailViewPickupLocation}
     * @memberof TransportDetailView
     */
    'deliveryLocation': WasteStreamDetailViewPickupLocation;
    /**
     * 
     * @type {Instant}
     * @memberof TransportDetailView
     */
    'deliveryDateTime': Instant;
    /**
     * 
     * @type {string}
     * @memberof TransportDetailView
     */
    'transportType': string;
    /**
     * 
     * @type {string}
     * @memberof TransportDetailView
     */
    'status': TransportDetailViewStatusEnum;
    /**
     * 
     * @type {TruckView}
     * @memberof TransportDetailView
     */
    'truck'?: TruckView;
    /**
     * 
     * @type {DriverView}
     * @memberof TransportDetailView
     */
    'driver'?: DriverView;
    /**
     * 
     * @type {string}
     * @memberof TransportDetailView
     */
    'note': string;
    /**
     * 
     * @type {number}
     * @memberof TransportDetailView
     */
    'transportHours'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransportDetailView
     */
    'sequenceNumber': number;
    /**
     * 
     * @type {Instant}
     * @memberof TransportDetailView
     */
    'updatedAt'?: Instant;
    /**
     * 
     * @type {WasteContainerView}
     * @memberof TransportDetailView
     */
    'wasteContainer'?: WasteContainerView;
}

export const TransportDetailViewStatusEnum = {
    Unplanned: 'UNPLANNED',
    Planned: 'PLANNED',
    Finished: 'FINISHED'
} as const;

export type TransportDetailViewStatusEnum = typeof TransportDetailViewStatusEnum[keyof typeof TransportDetailViewStatusEnum];


