/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyDto } from './company-dto';

/**
 * 
 * @export
 * @interface TruckDto
 */
export interface TruckDto {
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'licensePlate': string;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'brand'?: string;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'description'?: string;
    /**
     * 
     * @type {CompanyDto}
     * @memberof TruckDto
     */
    'carrierParty'?: CompanyDto;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'updatedBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof TruckDto
     */
    'displayName': string;
}

