/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyDataResponse } from './company-data-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ConsignorDataResponse } from './consignor-data-response';
// May contain unused imports in some cases
// @ts-ignore
import type { PickupLocationDataResponse } from './pickup-location-data-response';

/**
 * 
 * @export
 * @interface ValidationRequestDataResponse
 */
export interface ValidationRequestDataResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'wasteStreamNumber': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'routeCollection'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'collectorsScheme'?: string;
    /**
     * 
     * @type {ConsignorDataResponse}
     * @memberof ValidationRequestDataResponse
     */
    'consignor'?: ConsignorDataResponse;
    /**
     * 
     * @type {PickupLocationDataResponse}
     * @memberof ValidationRequestDataResponse
     */
    'pickupLocation'?: PickupLocationDataResponse;
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'deliveryLocation'?: string;
    /**
     * 
     * @type {CompanyDataResponse}
     * @memberof ValidationRequestDataResponse
     */
    'consignorParty'?: CompanyDataResponse;
    /**
     * 
     * @type {CompanyDataResponse}
     * @memberof ValidationRequestDataResponse
     */
    'collectorParty'?: CompanyDataResponse;
    /**
     * 
     * @type {CompanyDataResponse}
     * @memberof ValidationRequestDataResponse
     */
    'dealerParty'?: CompanyDataResponse;
    /**
     * 
     * @type {CompanyDataResponse}
     * @memberof ValidationRequestDataResponse
     */
    'brokerParty'?: CompanyDataResponse;
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'wasteCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'wasteName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRequestDataResponse
     */
    'processingMethod'?: string;
}

