/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VatRateRequest
 */
export interface VatRateRequest {
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'vatCode': string;
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'percentage': string;
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'validFrom': string;
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'validTo'?: string;
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'countryCode': string;
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof VatRateRequest
     */
    'taxScenario': VatRateRequestTaxScenarioEnum;
}

export const VatRateRequestTaxScenarioEnum = {
    Standard: 'STANDARD',
    ReverseCharge: 'REVERSE_CHARGE',
    ZeroRatedExport: 'ZERO_RATED_EXPORT',
    Exempt: 'EXEMPT'
} as const;

export type VatRateRequestTaxScenarioEnum = typeof VatRateRequestTaxScenarioEnum[keyof typeof VatRateRequestTaxScenarioEnum];


