/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyView } from './company-view';
// May contain unused imports in some cases
// @ts-ignore
import type { DutchAddressView } from './dutch-address-view';
// May contain unused imports in some cases
// @ts-ignore
import type { NoPickupView } from './no-pickup-view';
// May contain unused imports in some cases
// @ts-ignore
import type { PickupCompanyView } from './pickup-company-view';
// May contain unused imports in some cases
// @ts-ignore
import type { ProjectLocationView } from './project-location-view';
// May contain unused imports in some cases
// @ts-ignore
import type { ProximityDescriptionView } from './proximity-description-view';

/**
 * @type WasteStreamDetailViewPickupLocation
 * @export
 */
export type WasteStreamDetailViewPickupLocation = DutchAddressView | NoPickupView | PickupCompanyView | ProjectLocationView | ProximityDescriptionView;


