/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WasteTransportRequest
 */
export interface WasteTransportRequest {
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'pickupDateTime': string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'deliveryDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'containerOperation': WasteTransportRequestContainerOperationEnum;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'transportType': WasteTransportRequestTransportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'driverId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'carrierPartyId': string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'truckId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'containerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'note': string;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'wasteStreamNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof WasteTransportRequest
     */
    'weight': number;
    /**
     * 
     * @type {string}
     * @memberof WasteTransportRequest
     */
    'unit': string;
    /**
     * 
     * @type {number}
     * @memberof WasteTransportRequest
     */
    'quantity': number;
}

export const WasteTransportRequestContainerOperationEnum = {
    Exchange: 'EXCHANGE',
    Pickup: 'PICKUP',
    Empty: 'EMPTY',
    Delivery: 'DELIVERY'
} as const;

export type WasteTransportRequestContainerOperationEnum = typeof WasteTransportRequestContainerOperationEnum[keyof typeof WasteTransportRequestContainerOperationEnum];
export const WasteTransportRequestTransportTypeEnum = {
    Container: 'CONTAINER',
    Waste: 'WASTE'
} as const;

export type WasteTransportRequestTransportTypeEnum = typeof WasteTransportRequestTransportTypeEnum[keyof typeof WasteTransportRequestTransportTypeEnum];


