/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WasteStreamByCompanyView
 */
export interface WasteStreamByCompanyView {
    /**
     * 
     * @type {string}
     * @memberof WasteStreamByCompanyView
     */
    'wasteStreamNumber': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamByCompanyView
     */
    'wasteName': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamByCompanyView
     */
    'pickupLocation': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamByCompanyView
     */
    'status': string;
}

