/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContainerLocation } from './container-location';

/**
 * 
 * @export
 * @interface WasteContainerRequest
 */
export interface WasteContainerRequest {
    /**
     * 
     * @type {string}
     * @memberof WasteContainerRequest
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof WasteContainerRequest
     */
    'id': string;
    /**
     * 
     * @type {ContainerLocation}
     * @memberof WasteContainerRequest
     */
    'location'?: ContainerLocation;
    /**
     * 
     * @type {string}
     * @memberof WasteContainerRequest
     */
    'notes'?: string;
}

