/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyView } from './company-view';
// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryLocationView } from './delivery-location-view';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteContainerViewLocation } from './waste-container-view-location';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteTypeView } from './waste-type-view';
// May contain unused imports in some cases
// @ts-ignore
import type { WeightTicketDetailViewConsignorParty } from './weight-ticket-detail-view-consignor-party';

/**
 * 
 * @export
 * @interface WasteStreamDetailView
 */
export interface WasteStreamDetailView {
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'wasteStreamNumber': string;
    /**
     * 
     * @type {WasteTypeView}
     * @memberof WasteStreamDetailView
     */
    'wasteType': WasteTypeView;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'collectionType': string;
    /**
     * 
     * @type {WasteContainerViewLocation}
     * @memberof WasteStreamDetailView
     */
    'pickupLocation'?: WasteContainerViewLocation;
    /**
     * 
     * @type {DeliveryLocationView}
     * @memberof WasteStreamDetailView
     */
    'deliveryLocation': DeliveryLocationView;
    /**
     * 
     * @type {WeightTicketDetailViewConsignorParty}
     * @memberof WasteStreamDetailView
     */
    'consignorParty': WeightTicketDetailViewConsignorParty;
    /**
     * 
     * @type {number}
     * @memberof WasteStreamDetailView
     */
    'consignorClassification': number;
    /**
     * 
     * @type {CompanyView}
     * @memberof WasteStreamDetailView
     */
    'pickupParty': CompanyView;
    /**
     * 
     * @type {CompanyView}
     * @memberof WasteStreamDetailView
     */
    'dealerParty'?: CompanyView;
    /**
     * 
     * @type {CompanyView}
     * @memberof WasteStreamDetailView
     */
    'collectorParty'?: CompanyView;
    /**
     * 
     * @type {CompanyView}
     * @memberof WasteStreamDetailView
     */
    'brokerParty'?: CompanyView;
    /**
     * 
     * @type {number}
     * @memberof WasteStreamDetailView
     */
    'materialId'?: number;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamDetailView
     */
    'updatedBy'?: string;
}

