/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WasteTypeRequest
 */
export interface WasteTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof WasteTypeRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof WasteTypeRequest
     */
    'euralCode': string;
    /**
     * 
     * @type {string}
     * @memberof WasteTypeRequest
     */
    'processingMethod': string;
}

