/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WasteStreamListView
 */
export interface WasteStreamListView {
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'wasteStreamNumber': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'wasteName': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'euralCode': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'processingMethodCode': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'consignorPartyChamberOfCommerceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'consignorPartyName': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'pickupLocationStreetName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'pickupLocationPostalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'pickupLocationNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'pickupLocationCity': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'deliveryLocationStreetName': string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'deliveryLocationPostalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'deliveryLocationNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteStreamListView
     */
    'deliveryLocationCity': string;
}

