/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyView } from './company-view';
// May contain unused imports in some cases
// @ts-ignore
import type { LocalDateTime } from './local-date-time';
// May contain unused imports in some cases
// @ts-ignore
import type { WasteContainerViewLocation } from './waste-container-view-location';
// May contain unused imports in some cases
// @ts-ignore
import type { WeightTicketDetailViewConsignorParty } from './weight-ticket-detail-view-consignor-party';
// May contain unused imports in some cases
// @ts-ignore
import type { WeightTicketLineView } from './weight-ticket-line-view';

/**
 * 
 * @export
 * @interface WeightTicketDetailView
 */
export interface WeightTicketDetailView {
    /**
     * 
     * @type {number}
     * @memberof WeightTicketDetailView
     */
    'id': number;
    /**
     * 
     * @type {WeightTicketDetailViewConsignorParty}
     * @memberof WeightTicketDetailView
     */
    'consignorParty': WeightTicketDetailViewConsignorParty;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'status': string;
    /**
     * 
     * @type {Array<WeightTicketLineView>}
     * @memberof WeightTicketDetailView
     */
    'lines': Array<WeightTicketLineView>;
    /**
     * 
     * @type {number}
     * @memberof WeightTicketDetailView
     */
    'secondWeighingValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'secondWeighingUnit'?: string;
    /**
     * 
     * @type {number}
     * @memberof WeightTicketDetailView
     */
    'tarraWeightValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'tarraWeightUnit'?: string;
    /**
     * 
     * @type {CompanyView}
     * @memberof WeightTicketDetailView
     */
    'carrierParty'?: CompanyView;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'direction': string;
    /**
     * 
     * @type {WasteContainerViewLocation}
     * @memberof WeightTicketDetailView
     */
    'pickupLocation'?: WasteContainerViewLocation;
    /**
     * 
     * @type {WasteContainerViewLocation}
     * @memberof WeightTicketDetailView
     */
    'deliveryLocation'?: WasteContainerViewLocation;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'truckLicensePlate'?: string;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'reclamation'?: string;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'note'?: string;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'cancellationReason'?: string;
    /**
     * 
     * @type {number}
     * @memberof WeightTicketDetailView
     */
    'linkedInvoiceId'?: number;
    /**
     * 
     * @type {LocalDateTime}
     * @memberof WeightTicketDetailView
     */
    'createdAt'?: LocalDateTime;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'createdByName'?: string;
    /**
     * 
     * @type {LocalDateTime}
     * @memberof WeightTicketDetailView
     */
    'updatedAt'?: LocalDateTime;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'updatedByName'?: string;
    /**
     * 
     * @type {LocalDateTime}
     * @memberof WeightTicketDetailView
     */
    'weightedAt'?: LocalDateTime;
    /**
     * 
     * @type {string}
     * @memberof WeightTicketDetailView
     */
    'pdfUrl'?: string;
}

