/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WeightRequest
 */
export interface WeightRequest {
    /**
     * 
     * @type {string}
     * @memberof WeightRequest
     */
    'value': string;
    /**
     * 
     * @type {string}
     * @memberof WeightRequest
     */
    'unit': WeightRequestUnitEnum;
}

export const WeightRequestUnitEnum = {
    Kg: 'KG'
} as const;

export type WeightRequestUnitEnum = typeof WeightRequestUnitEnum[keyof typeof WeightRequestUnitEnum];


