INSERT INTO auth.users (instance_id,
                        id,
                        aud,
                        role,
                        email,
                        encrypted_password,
                        email_confirmed_at,
                        recovery_sent_at,
                        last_sign_in_at,
                        raw_app_meta_data,
                        raw_user_meta_data,
                        created_at,
                        updated_at,
                        confirmation_token,
                        email_change,
                        email_change_token_new,
                        recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000',
        uuid_generate_v4(),
        'authenticated',
        'authenticated',
        'calvin@eazysoftware.nl',
        crypt('password123', gen_salt('bf')),
        current_timestamp,
        current_timestamp,
        current_timestamp,
        '{"provider":"email","providers":["email"]}',
        jsonb_build_object('first_name', 'Calvin', 'last_name', 'Richardson', 'roles', array ['admin', 'planner']),
        current_timestamp,
        current_timestamp,
        '',
        '',
        '',
        '');

insert into public.eural (code, description)
values ('17 04', 'metaal (inclusief legeringen)'),
       ('17 04 01 c', 'koper, brons en messing'),
       ('17 04 02 c', 'aluminium'),
       ('17 04 03 c', 'lood'),
       ('17 04 04 c', 'zink'),
       ('17 04 05 c', 'ijzer en staal'),
       ('17 04 06 c', 'tin'),
       ('17 04 07 c', 'gemengde metalen'),
       ('17 04 09* c', 'metaalafval dat met gevaarlijke stoffen is verontreinigd'),
       ('17 04 10* c', 'kabels die olie, koolteer of andere gevaarlijke stoffen bevatten'),
       ('17 04 11 c', 'niet onder 17 04 10 vallende kabels)');