SET search_path TO public, extensions;

INSERT INTO auth.users (instance_id,
                        id,
                        aud,
                        role,
                        email,
                        encrypted_password,
                        email_confirmed_at,
                        recovery_sent_at,
                        last_sign_in_at,
                        raw_app_meta_data,
                        raw_user_meta_data,
                        created_at,
                        updated_at,
                        confirmation_token,
                        email_change,
                        email_change_token_new,
                        recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000',
        gen_random_uuid(),
        'authenticated',
        'authenticated',
        'admin@eazyrecycling.nl',
        crypt('password123', gen_salt('bf')),
        current_timestamp,
        current_timestamp,
        current_timestamp,
        '{"provider":"email","providers":["email"]}',
        jsonb_build_object('first_name', 'Aad', 'last_name', 'Admin', 'roles', array ['admin', 'planner']),
        current_timestamp,
        current_timestamp,
        '',
        '',
        '',
        ''),
        ('00000000-0000-0000-0000-000000000000',
        gen_random_uuid(),
        'authenticated',
        'authenticated',
        'planner@eazyrecycling.nl',
        crypt('password123', gen_salt('bf')),
        current_timestamp,
        current_timestamp,
        current_timestamp,
        '{"provider":"email","providers":["email"]}',
        jsonb_build_object('first_name', 'Peter', 'last_name', 'Planner', 'roles', array ['planner']),
        current_timestamp,
        current_timestamp,
        '',
        '',
        '',
        ''),
        ('00000000-0000-0000-0000-000000000000',
        gen_random_uuid(),
        'authenticated',
        'authenticated',
        'chauffeur@eazyrecycling.nl',
        crypt('password123', gen_salt('bf')),
        current_timestamp,
        current_timestamp,
        current_timestamp,
        '{"provider":"email","providers":["email"]}',
        jsonb_build_object('first_name', 'Sjaak', 'last_name', 'Chauffeur', 'roles', array ['chauffeur']),
        current_timestamp,
        current_timestamp,
        '',
        '',
        '',
        '');

INSERT INTO "public"."trucks" ("license_plate", "brand", "model", "updated_at") VALUES
	('86-BVB-6', 'Scania', 'Haakarm', '2025-09-19 10:56:08.866574+00');

INSERT INTO "public"."companies" ("id", "name", "chamber_of_commerce_id", "street_name", "postal_code", "city", "vihb_id", "updated_at", "building_name", "building_number", "country") VALUES
	('6a683b2a-96d6-454c-8cae-4a7e2a03f249', 'Eazy Recycling', '12345678', 'Straat', '1234 AB', 'Rotterdam', '123456VIXX', '2025-09-19 11:22:15.258406+00', NULL, '8', 'Nederland'),
	('b6d76e22-998b-4842-826d-8d42853e87a5', 'King Customer', '87654321', 'Coolsingel', '3011 AD', ' Rotterdam', NULL, '2025-09-19 11:23:33.417513+00', NULL, '40', 'Nederland');


insert into public.eural (code, description)
values ('16 01 17', 'ferrometalen'),
       ('16 01 18', 'non-ferrometalen'),
       ('17 04 01', 'koper, brons en messing'),
       ('17 04 02', 'aluminium'),
       ('17 04 03', 'lood'),
       ('17 04 04', 'zink'),
       ('17 04 05', 'ijzer en staal'),
       ('17 04 06', 'tin'),
       ('17 04 07', 'gemengde metalen'),
       ('20 01 40', 'metalen'),
       ('16 02 14', 'niet onder 16 02 09 tot en met 16 02 13 vallende afgedankte apparatuur'),
       ('16 02 16', 'niet onder 16 02 15 vallende uit afgedankte apparatuur verwijderde onderdelen (trafo''s en elektromotoren)'),
       ('20 01 36', 'niet onder 20 01 21, 20 01 23 en 20 01 35 vallende afgedankte elektrische en elektronische apparatuur'),
       ('09 01 11*', 'wegwerpcamera''s met onder 16 06 01, 16 06 02 of 16 06 03 vermelde batterijen 09 01 12 niet onder 09
01 11 vallende wegwerpcamera''s met batterijen'),
       ('16 02 13*', 'niet onder 16 02 09 tot en met 16 02 12 vallende afgedankte apparatuur die gevaarlijke onderdelen
bevat'),
       ('16 02 15*', 'uit afgedankte apparatuur verwijderde gevaarlijke onderdelen'),
       ('20 01 35*', 'niet onder 20 01 21 en 20 01 23 vallende afgedankte elektrische en elektronische apparatuur die
gevaarlijke onderdelen bevat'),
       ('16 06 01*', 'loodaccu''s'),
       ('17 04 11', 'niet onder 17 04 10 vallende kabels'),
       ('20 01 33*', 'onder 16 06 01, 16 06 02 of 16 06 03 vermelde batterijen en accu’s alsmede ongesorteerde mengsels van batterijen en accu''s die
dergelijke batterijen en accu''s bevatten'),
       ('20 01 34', 'niet onder 20 01 33 vallende batterijen en accu''s'),
       ('16 06 02*', 'NiCd-batterijen'),
       ('19 12 10', 'brandbaar afval (RDF)'),
       ('19 12 11*', 'overig afval (inclusief mengsels van materialen) van mechanische afvalverwerking dat gevaarlijke stoffen bevat'),
       ('19 12 12 o', 'overig, niet onder 19 12 11 vallend afval (inclusief mengsels van materialen) van mechanische afvalverwerking');

INSERT INTO processing_methods (code, description)
VALUES ('A.01', 'Bewaren'),
       ('A.02', 'Overslag / opbulken'),
       ('B.01', 'Inzetten als veevoer'),
       ('B.02', 'Inzetten als meststof'),
       ('B.03', 'Inzetten als bouwstof'),
       ('B.04', 'Inzetten als brandstof'),
       ('B.05', 'Overig inzetten als grondstof'),
       ('C.01', 'Breken'),
       ('C.02', 'Shredden / knippen'),
       ('C.03', 'Sorteren/scheiden'),
       ('C.04', 'Immobiliseren voor hergebruik'),
       ('D.01', 'Chemisch/fysisch scheiden'),
       ('D.02', 'ONO is ontgiften, neutraliseren en ontwateren'),
       ('D.03', 'Destilleren'),
       ('D.04', 'Metaal terugwinnen (chemisch)'),
       ('D.05', 'Extractief reinigen (grond)'),
       ('D.06', 'Oxidatie onder hoge druk'),
       ('E.01', 'Vergisten'),
       ('E.02', 'Composteren, anaeroob'),
       ('E.03', 'Composteren, aeroob'),
       ('E.04', 'Biologisch reinigen (water)'),
       ('E.05', 'Biologisch reinigen (grond)'),
       ('F.01', 'Verbranden in roosterovens'),
       ('F.02', 'Verbranden in draaitrommelovens'),
       ('F.03', 'Pyrolyse'),
       ('F.04', 'Vergassen'),
       ('F.05', 'Uitgloeien (grond)'),
       ('F.06', 'Verbranden met terugwinnen materiaal (chloor, zwavel ..)'),
       ('F.07', 'Verbranden met terugwinnen energie (bijstoken)'),
       ('G.01', 'Direct storten'),
       ('G.02', 'Immobiliseren');

INSERT INTO "public"."waste_containers" ("id", "type", "created_at", "updated_at", "location_company_id", "street_name", "postal_code", "city", "building_number", "building_name", "country", "notes") VALUES
	('40M001', NULL, '2025-09-22 08:04:13.247323+00', '2025-09-22 08:04:13.247323+00', NULL, '', '', '', '', NULL, 'Nederland', '');