revoke delete on table "public"."goods_items" from "anon";

revoke insert on table "public"."goods_items" from "anon";

revoke references on table "public"."goods_items" from "anon";

revoke select on table "public"."goods_items" from "anon";

revoke trigger on table "public"."goods_items" from "anon";

revoke truncate on table "public"."goods_items" from "anon";

revoke update on table "public"."goods_items" from "anon";

revoke delete on table "public"."goods_items" from "authenticated";

revoke insert on table "public"."goods_items" from "authenticated";

revoke references on table "public"."goods_items" from "authenticated";

revoke select on table "public"."goods_items" from "authenticated";

revoke trigger on table "public"."goods_items" from "authenticated";

revoke truncate on table "public"."goods_items" from "authenticated";

revoke update on table "public"."goods_items" from "authenticated";

revoke delete on table "public"."goods_items" from "service_role";

revoke insert on table "public"."goods_items" from "service_role";

revoke references on table "public"."goods_items" from "service_role";

revoke select on table "public"."goods_items" from "service_role";

revoke trigger on table "public"."goods_items" from "service_role";

revoke truncate on table "public"."goods_items" from "service_role";

revoke update on table "public"."goods_items" from "service_role";

alter table "public"."goods_items" drop constraint "goods_items_waste_stream_number_fkey";

alter table "public"."transports" drop constraint "transports_goods_item_id_fkey";

alter table "public"."goods_items" drop constraint "goods_items_pkey";

drop index if exists "public"."goods_items_pkey";

drop table "public"."goods_items";


  create table "public"."transport_goods" (
    "id" bigint generated by default as identity not null,
    "transport_id" uuid not null,
    "net_net_weight" integer not null,
    "quantity" integer not null,
    "unit" text,
    "waste_stream_number" text not null
      );


alter table "public"."transport_goods" enable row level security;

alter table "public"."transports" drop column "goods_item_id";

CREATE UNIQUE INDEX transport_goods_pkey ON public.transport_goods USING btree (id);

alter table "public"."transport_goods" add constraint "transport_goods_pkey" PRIMARY KEY using index "transport_goods_pkey";

alter table "public"."transport_goods" add constraint "transport_goods_transport_id_fkey" FOREIGN KEY (transport_id) REFERENCES public.transports(id) not valid;

alter table "public"."transport_goods" validate constraint "transport_goods_transport_id_fkey";

alter table "public"."transport_goods" add constraint "transport_goods_waste_stream_number_fkey" FOREIGN KEY (waste_stream_number) REFERENCES public.waste_streams(number) not valid;

alter table "public"."transport_goods" validate constraint "transport_goods_waste_stream_number_fkey";

set check_function_bodies = off;

grant delete on table "public"."transport_goods" to "anon";

grant insert on table "public"."transport_goods" to "anon";

grant references on table "public"."transport_goods" to "anon";

grant select on table "public"."transport_goods" to "anon";

grant trigger on table "public"."transport_goods" to "anon";

grant truncate on table "public"."transport_goods" to "anon";

grant update on table "public"."transport_goods" to "anon";

grant delete on table "public"."transport_goods" to "authenticated";

grant insert on table "public"."transport_goods" to "authenticated";

grant references on table "public"."transport_goods" to "authenticated";

grant select on table "public"."transport_goods" to "authenticated";

grant trigger on table "public"."transport_goods" to "authenticated";

grant truncate on table "public"."transport_goods" to "authenticated";

grant update on table "public"."transport_goods" to "authenticated";

grant delete on table "public"."transport_goods" to "service_role";

grant insert on table "public"."transport_goods" to "service_role";

grant references on table "public"."transport_goods" to "service_role";

grant select on table "public"."transport_goods" to "service_role";

grant trigger on table "public"."transport_goods" to "service_role";

grant truncate on table "public"."transport_goods" to "service_role";

grant update on table "public"."transport_goods" to "service_role";
