create sequence "public"."catalog_item_categories_id_seq";

create sequence "public"."catalog_items_id_seq";


  create table "public"."catalog_item_categories" (
    "id" bigint not null default nextval('public.catalog_item_categories_id_seq'::regclass),
    "type" text not null,
    "code" text not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "created_by" text,
    "last_modified_at" timestamp with time zone not null default now(),
    "last_modified_by" text
      );


alter table "public"."catalog_item_categories" enable row level security;


  create table "public"."catalog_items" (
    "id" bigint not null default nextval('public.catalog_items_id_seq'::regclass),
    "type" text not null,
    "code" text not null,
    "name" text not null,
    "unit_of_measure" text not null,
    "vat_code" text not null,
    "category_id" bigint,
    "consignor_party_id" uuid,
    "default_price" numeric(15,4),
    "status" text not null,
    "purchase_account_number" text,
    "sales_account_number" text,
    "created_at" timestamp with time zone not null default now(),
    "created_by" text,
    "last_modified_at" timestamp with time zone not null default now(),
    "last_modified_by" text
      );


alter table "public"."catalog_items" enable row level security;


  create table "public"."lma_import_errors" (
    "id" uuid not null,
    "import_batch_id" uuid not null,
    "row_number" integer not null,
    "waste_stream_number" text,
    "error_code" text not null,
    "error_message" text not null,
    "raw_data" jsonb,
    "created_at" timestamp with time zone not null default now(),
    "resolved_at" timestamp with time zone,
    "resolved_by" text
      );


alter table "public"."lma_import_errors" enable row level security;


  create table "public"."product_categories" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "created_by" text,
    "last_modified_at" timestamp with time zone not null,
    "last_modified_by" text
      );


alter table "public"."product_categories" enable row level security;


  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "product_category_id" bigint,
    "unit_of_measure" text not null,
    "vat_code" text not null,
    "gl_account_code" text not null,
    "status" text not null,
    "default_price" numeric not null,
    "description" text not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" text,
    "last_modified_at" timestamp with time zone,
    "last_modified_by" text
      );


alter table "public"."products" enable row level security;

alter table "public"."company_roles" enable row level security;

alter table "public"."exact_tokens" enable row level security;

alter table "public"."materials" add column "gl_account_code" text;

alter table "public"."waste_streams" add column "catalog_item_id" bigint;

alter table "public"."weight_ticket_declaration_snapshots" enable row level security;

alter table "public"."weight_ticket_lines" add column "catalog_item_id" bigint not null;

alter table "public"."weight_ticket_lines" alter column "waste_stream_number" set default ''::text;

alter table "public"."weight_ticket_lines" alter column "waste_stream_number" drop not null;

alter sequence "public"."catalog_item_categories_id_seq" owned by "public"."catalog_item_categories"."id";

alter sequence "public"."catalog_items_id_seq" owned by "public"."catalog_items"."id";

CREATE UNIQUE INDEX catalog_item_categories_code_key ON public.catalog_item_categories USING btree (code);

CREATE UNIQUE INDEX catalog_item_categories_pkey ON public.catalog_item_categories USING btree (id);

CREATE UNIQUE INDEX catalog_items_code_key ON public.catalog_items USING btree (code);

CREATE UNIQUE INDEX catalog_items_pkey ON public.catalog_items USING btree (id);

CREATE INDEX idx_catalog_item_categories_type ON public.catalog_item_categories USING btree (type);

CREATE INDEX idx_catalog_items_category ON public.catalog_items USING btree (category_id);

CREATE INDEX idx_catalog_items_consignor ON public.catalog_items USING btree (consignor_party_id);

CREATE INDEX idx_catalog_items_status ON public.catalog_items USING btree (status);

CREATE INDEX idx_catalog_items_type ON public.catalog_items USING btree (type);

CREATE UNIQUE INDEX lma_import_errors_pkey ON public.lma_import_errors USING btree (id);

CREATE UNIQUE INDEX product_categories_code_key ON public.product_categories USING btree (code);

CREATE UNIQUE INDEX product_categories_pkey ON public.product_categories USING btree (id);

CREATE UNIQUE INDEX products_code_key ON public.products USING btree (code);

alter table "public"."catalog_item_categories" add constraint "catalog_item_categories_pkey" PRIMARY KEY using index "catalog_item_categories_pkey";

alter table "public"."catalog_items" add constraint "catalog_items_pkey" PRIMARY KEY using index "catalog_items_pkey";

alter table "public"."lma_import_errors" add constraint "lma_import_errors_pkey" PRIMARY KEY using index "lma_import_errors_pkey";

alter table "public"."product_categories" add constraint "product_categories_pkey" PRIMARY KEY using index "product_categories_pkey";

alter table "public"."catalog_item_categories" add constraint "catalog_item_categories_code_key" UNIQUE using index "catalog_item_categories_code_key";

alter table "public"."catalog_items" add constraint "catalog_items_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.catalog_item_categories(id) not valid;

alter table "public"."catalog_items" validate constraint "catalog_items_category_id_fkey";

alter table "public"."catalog_items" add constraint "catalog_items_code_key" UNIQUE using index "catalog_items_code_key";

alter table "public"."catalog_items" add constraint "catalog_items_consignor_party_id_fkey" FOREIGN KEY (consignor_party_id) REFERENCES public.companies(id) not valid;

alter table "public"."catalog_items" validate constraint "catalog_items_consignor_party_id_fkey";

alter table "public"."product_categories" add constraint "product_categories_code_key" UNIQUE using index "product_categories_code_key";

alter table "public"."products" add constraint "products_code_key" UNIQUE using index "products_code_key";

alter table "public"."waste_streams" add constraint "waste_streams_catalog_item_id_fkey" FOREIGN KEY (catalog_item_id) REFERENCES public.catalog_items(id) not valid;

alter table "public"."waste_streams" validate constraint "waste_streams_catalog_item_id_fkey";

alter table "public"."weight_ticket_lines" add constraint "weight_ticket_lines_catalog_item_id_fkey" FOREIGN KEY (catalog_item_id) REFERENCES public.catalog_items(id) not valid;

alter table "public"."weight_ticket_lines" validate constraint "weight_ticket_lines_catalog_item_id_fkey";

grant delete on table "public"."catalog_item_categories" to "anon";

grant insert on table "public"."catalog_item_categories" to "anon";

grant references on table "public"."catalog_item_categories" to "anon";

grant select on table "public"."catalog_item_categories" to "anon";

grant trigger on table "public"."catalog_item_categories" to "anon";

grant truncate on table "public"."catalog_item_categories" to "anon";

grant update on table "public"."catalog_item_categories" to "anon";

grant delete on table "public"."catalog_item_categories" to "authenticated";

grant insert on table "public"."catalog_item_categories" to "authenticated";

grant references on table "public"."catalog_item_categories" to "authenticated";

grant select on table "public"."catalog_item_categories" to "authenticated";

grant trigger on table "public"."catalog_item_categories" to "authenticated";

grant truncate on table "public"."catalog_item_categories" to "authenticated";

grant update on table "public"."catalog_item_categories" to "authenticated";

grant delete on table "public"."catalog_item_categories" to "postgres";

grant insert on table "public"."catalog_item_categories" to "postgres";

grant references on table "public"."catalog_item_categories" to "postgres";

grant select on table "public"."catalog_item_categories" to "postgres";

grant trigger on table "public"."catalog_item_categories" to "postgres";

grant truncate on table "public"."catalog_item_categories" to "postgres";

grant update on table "public"."catalog_item_categories" to "postgres";

grant delete on table "public"."catalog_item_categories" to "service_role";

grant insert on table "public"."catalog_item_categories" to "service_role";

grant references on table "public"."catalog_item_categories" to "service_role";

grant select on table "public"."catalog_item_categories" to "service_role";

grant trigger on table "public"."catalog_item_categories" to "service_role";

grant truncate on table "public"."catalog_item_categories" to "service_role";

grant update on table "public"."catalog_item_categories" to "service_role";

grant delete on table "public"."catalog_items" to "anon";

grant insert on table "public"."catalog_items" to "anon";

grant references on table "public"."catalog_items" to "anon";

grant select on table "public"."catalog_items" to "anon";

grant trigger on table "public"."catalog_items" to "anon";

grant truncate on table "public"."catalog_items" to "anon";

grant update on table "public"."catalog_items" to "anon";

grant delete on table "public"."catalog_items" to "authenticated";

grant insert on table "public"."catalog_items" to "authenticated";

grant references on table "public"."catalog_items" to "authenticated";

grant select on table "public"."catalog_items" to "authenticated";

grant trigger on table "public"."catalog_items" to "authenticated";

grant truncate on table "public"."catalog_items" to "authenticated";

grant update on table "public"."catalog_items" to "authenticated";

grant delete on table "public"."catalog_items" to "postgres";

grant insert on table "public"."catalog_items" to "postgres";

grant references on table "public"."catalog_items" to "postgres";

grant select on table "public"."catalog_items" to "postgres";

grant trigger on table "public"."catalog_items" to "postgres";

grant truncate on table "public"."catalog_items" to "postgres";

grant update on table "public"."catalog_items" to "postgres";

grant delete on table "public"."catalog_items" to "service_role";

grant insert on table "public"."catalog_items" to "service_role";

grant references on table "public"."catalog_items" to "service_role";

grant select on table "public"."catalog_items" to "service_role";

grant trigger on table "public"."catalog_items" to "service_role";

grant truncate on table "public"."catalog_items" to "service_role";

grant update on table "public"."catalog_items" to "service_role";

grant delete on table "public"."lma_import_errors" to "anon";

grant insert on table "public"."lma_import_errors" to "anon";

grant references on table "public"."lma_import_errors" to "anon";

grant select on table "public"."lma_import_errors" to "anon";

grant trigger on table "public"."lma_import_errors" to "anon";

grant truncate on table "public"."lma_import_errors" to "anon";

grant update on table "public"."lma_import_errors" to "anon";

grant delete on table "public"."lma_import_errors" to "authenticated";

grant insert on table "public"."lma_import_errors" to "authenticated";

grant references on table "public"."lma_import_errors" to "authenticated";

grant select on table "public"."lma_import_errors" to "authenticated";

grant trigger on table "public"."lma_import_errors" to "authenticated";

grant truncate on table "public"."lma_import_errors" to "authenticated";

grant update on table "public"."lma_import_errors" to "authenticated";

grant delete on table "public"."lma_import_errors" to "service_role";

grant insert on table "public"."lma_import_errors" to "service_role";

grant references on table "public"."lma_import_errors" to "service_role";

grant select on table "public"."lma_import_errors" to "service_role";

grant trigger on table "public"."lma_import_errors" to "service_role";

grant truncate on table "public"."lma_import_errors" to "service_role";

grant update on table "public"."lma_import_errors" to "service_role";

grant delete on table "public"."product_categories" to "anon";

grant insert on table "public"."product_categories" to "anon";

grant references on table "public"."product_categories" to "anon";

grant select on table "public"."product_categories" to "anon";

grant trigger on table "public"."product_categories" to "anon";

grant truncate on table "public"."product_categories" to "anon";

grant update on table "public"."product_categories" to "anon";

grant delete on table "public"."product_categories" to "authenticated";

grant insert on table "public"."product_categories" to "authenticated";

grant references on table "public"."product_categories" to "authenticated";

grant select on table "public"."product_categories" to "authenticated";

grant trigger on table "public"."product_categories" to "authenticated";

grant truncate on table "public"."product_categories" to "authenticated";

grant update on table "public"."product_categories" to "authenticated";

grant delete on table "public"."product_categories" to "postgres";

grant insert on table "public"."product_categories" to "postgres";

grant references on table "public"."product_categories" to "postgres";

grant select on table "public"."product_categories" to "postgres";

grant trigger on table "public"."product_categories" to "postgres";

grant truncate on table "public"."product_categories" to "postgres";

grant update on table "public"."product_categories" to "postgres";

grant delete on table "public"."product_categories" to "service_role";

grant insert on table "public"."product_categories" to "service_role";

grant references on table "public"."product_categories" to "service_role";

grant select on table "public"."product_categories" to "service_role";

grant trigger on table "public"."product_categories" to "service_role";

grant truncate on table "public"."product_categories" to "service_role";

grant update on table "public"."product_categories" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "postgres";

grant insert on table "public"."products" to "postgres";

grant references on table "public"."products" to "postgres";

grant select on table "public"."products" to "postgres";

grant trigger on table "public"."products" to "postgres";

grant truncate on table "public"."products" to "postgres";

grant update on table "public"."products" to "postgres";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";


