create extension if not exists "btree_gist" with schema "public";


  create table "public"."material_groups" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "description" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
      );


alter table "public"."material_groups" enable row level security;


  create table "public"."material_prices" (
    "id" bigint generated by default as identity not null,
    "material_id" bigint not null,
    "price" numeric not null,
    "currency" text not null,
    "valid_from" timestamp with time zone not null,
    "valid_to" timestamp with time zone
      );


alter table "public"."material_prices" enable row level security;


  create table "public"."materials" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "material_group_id" bigint not null,
    "unit_of_measure" text not null,
    "vat_code" bigint not null,
    "created_at" timestamp with time zone not null,
    "status" text not null,
    "updated_at" timestamp with time zone
      );


alter table "public"."materials" enable row level security;


  create table "public"."vat_rates" (
    "vat_code" text not null,
    "percentage" numeric not null,
    "valid_from" timestamp with time zone not null,
    "valid_to" timestamp with time zone,
    "country_code" text not null,
    "description" text not null,
    "validity" tstzrange generated always as (tstzrange(valid_from, COALESCE(valid_to, 'infinity'::timestamp with time zone), '[)'::text)) stored
      );


alter table "public"."vat_rates" enable row level security;

CREATE UNIQUE INDEX material_group_code_key ON public.material_groups USING btree (code);

CREATE UNIQUE INDEX material_group_pkey ON public.material_groups USING btree (id);

CREATE UNIQUE INDEX material_prices_pkey ON public.material_prices USING btree (id);

CREATE UNIQUE INDEX materials_code_key ON public.materials USING btree (code);

CREATE UNIQUE INDEX materials_pkey ON public.materials USING btree (id);

select 1; 
-- CREATE INDEX vat_rates_no_overlap ON public.vat_rates USING gist (vat_code, country_code, validity);

CREATE UNIQUE INDEX vat_rates_pkey ON public.vat_rates USING btree (vat_code, country_code, valid_from);

alter table "public"."material_groups" add constraint "material_group_pkey" PRIMARY KEY using index "material_group_pkey";

alter table "public"."material_prices" add constraint "material_prices_pkey" PRIMARY KEY using index "material_prices_pkey";

alter table "public"."materials" add constraint "materials_pkey" PRIMARY KEY using index "materials_pkey";

alter table "public"."vat_rates" add constraint "vat_rates_pkey" PRIMARY KEY using index "vat_rates_pkey";

alter table "public"."material_groups" add constraint "material_group_code_key" UNIQUE using index "material_group_code_key";

alter table "public"."material_prices" add constraint "material_prices_material_id_fkey" FOREIGN KEY (material_id) REFERENCES public.materials(id) not valid;

alter table "public"."material_prices" validate constraint "material_prices_material_id_fkey";

alter table "public"."materials" add constraint "materials_code_key" UNIQUE using index "materials_code_key";

alter table "public"."vat_rates" add constraint "vat_rates_no_overlap" EXCLUDE USING gist (vat_code WITH =, country_code WITH =, validity WITH &&);

alter table "public"."vat_rates" add constraint "vat_rates_valid_range_chk" CHECK (((valid_to IS NULL) OR (valid_to > valid_from))) not valid;

alter table "public"."vat_rates" validate constraint "vat_rates_valid_range_chk";

grant delete on table "public"."material_groups" to "anon";

grant insert on table "public"."material_groups" to "anon";

grant references on table "public"."material_groups" to "anon";

grant select on table "public"."material_groups" to "anon";

grant trigger on table "public"."material_groups" to "anon";

grant truncate on table "public"."material_groups" to "anon";

grant update on table "public"."material_groups" to "anon";

grant delete on table "public"."material_groups" to "authenticated";

grant insert on table "public"."material_groups" to "authenticated";

grant references on table "public"."material_groups" to "authenticated";

grant select on table "public"."material_groups" to "authenticated";

grant trigger on table "public"."material_groups" to "authenticated";

grant truncate on table "public"."material_groups" to "authenticated";

grant update on table "public"."material_groups" to "authenticated";

grant delete on table "public"."material_groups" to "service_role";

grant insert on table "public"."material_groups" to "service_role";

grant references on table "public"."material_groups" to "service_role";

grant select on table "public"."material_groups" to "service_role";

grant trigger on table "public"."material_groups" to "service_role";

grant truncate on table "public"."material_groups" to "service_role";

grant update on table "public"."material_groups" to "service_role";

grant delete on table "public"."material_prices" to "anon";

grant insert on table "public"."material_prices" to "anon";

grant references on table "public"."material_prices" to "anon";

grant select on table "public"."material_prices" to "anon";

grant trigger on table "public"."material_prices" to "anon";

grant truncate on table "public"."material_prices" to "anon";

grant update on table "public"."material_prices" to "anon";

grant delete on table "public"."material_prices" to "authenticated";

grant insert on table "public"."material_prices" to "authenticated";

grant references on table "public"."material_prices" to "authenticated";

grant select on table "public"."material_prices" to "authenticated";

grant trigger on table "public"."material_prices" to "authenticated";

grant truncate on table "public"."material_prices" to "authenticated";

grant update on table "public"."material_prices" to "authenticated";

grant delete on table "public"."material_prices" to "service_role";

grant insert on table "public"."material_prices" to "service_role";

grant references on table "public"."material_prices" to "service_role";

grant select on table "public"."material_prices" to "service_role";

grant trigger on table "public"."material_prices" to "service_role";

grant truncate on table "public"."material_prices" to "service_role";

grant update on table "public"."material_prices" to "service_role";

grant delete on table "public"."materials" to "anon";

grant insert on table "public"."materials" to "anon";

grant references on table "public"."materials" to "anon";

grant select on table "public"."materials" to "anon";

grant trigger on table "public"."materials" to "anon";

grant truncate on table "public"."materials" to "anon";

grant update on table "public"."materials" to "anon";

grant delete on table "public"."materials" to "authenticated";

grant insert on table "public"."materials" to "authenticated";

grant references on table "public"."materials" to "authenticated";

grant select on table "public"."materials" to "authenticated";

grant trigger on table "public"."materials" to "authenticated";

grant truncate on table "public"."materials" to "authenticated";

grant update on table "public"."materials" to "authenticated";

grant delete on table "public"."materials" to "service_role";

grant insert on table "public"."materials" to "service_role";

grant references on table "public"."materials" to "service_role";

grant select on table "public"."materials" to "service_role";

grant trigger on table "public"."materials" to "service_role";

grant truncate on table "public"."materials" to "service_role";

grant update on table "public"."materials" to "service_role";

grant delete on table "public"."vat_rates" to "anon";

grant insert on table "public"."vat_rates" to "anon";

grant references on table "public"."vat_rates" to "anon";

grant select on table "public"."vat_rates" to "anon";

grant trigger on table "public"."vat_rates" to "anon";

grant truncate on table "public"."vat_rates" to "anon";

grant update on table "public"."vat_rates" to "anon";

grant delete on table "public"."vat_rates" to "authenticated";

grant insert on table "public"."vat_rates" to "authenticated";

grant references on table "public"."vat_rates" to "authenticated";

grant select on table "public"."vat_rates" to "authenticated";

grant trigger on table "public"."vat_rates" to "authenticated";

grant truncate on table "public"."vat_rates" to "authenticated";

grant update on table "public"."vat_rates" to "authenticated";

grant delete on table "public"."vat_rates" to "service_role";

grant insert on table "public"."vat_rates" to "service_role";

grant references on table "public"."vat_rates" to "service_role";

grant select on table "public"."vat_rates" to "service_role";

grant trigger on table "public"."vat_rates" to "service_role";

grant truncate on table "public"."vat_rates" to "service_role";

grant update on table "public"."vat_rates" to "service_role";


