create table if not exists companies (
                           updated_at timestamp(6),
                           id uuid not null,
                           building_name varchar(255),
                           building_number varchar(255),
                           chamber_of_commerce_id varchar(255) unique,
                           city varchar(255),
                           country varchar(255),
                           name varchar(255),
                           postal_code varchar(255),
                           street_name varchar(255),
                           vihb_id varchar(255) unique,
                           primary key (id)
);

create table if not exists drivers (
                         updated_at timestamp(6) not null,
                         id uuid not null,
                         first_name varchar(255) not null,
                         last_name varchar(255) not null,
                         primary key (id)
);

create table if not exists goods (
                       goods_item_id bigint unique,
                       updated_at timestamp(6) not null,
                       consignee_party_id uuid,
                       pickup_party_id uuid,
                       uuid uuid not null,
                       id varchar(255),
                       note varchar(255),
                       primary key (uuid)
);

create table if not exists goods_items (
                             net_net_weight integer not null,
                             quantity integer not null,
                             id bigint generated by default as identity,
                             container_number varchar(255),
                             eural_code varchar(255),
                             name varchar(255),
                             unit varchar(255),
                             waste_stream_number varchar(255),
                             primary key (id)
);

create table if not exists locations (
                           building_name varchar(255),
                           building_number varchar(255),
                           city varchar(255),
                           country varchar(255),
                           description varchar(255),
                           id varchar(255) not null,
                           location_type_code varchar(255),
                           postal_code varchar(255),
                           street_name varchar(255),
                           primary key (id)
);

create table if not exists transports (
                            delivery_date_time timestamp(6),
                            pickup_date_time timestamp(6),
                            updated_at timestamp(6) not null,
                            carrier_party_id uuid,
                            consignor_party_id uuid,
                            driver_id uuid,
                            goods_id uuid unique,
                            id uuid not null,
                            container_type varchar(255),
                            delivery_location_id varchar(255) unique,
                            pickup_location_id varchar(255) unique,
                            transport_type varchar(255) check (transport_type in ('EXCHANGE','PICKUP','EMPTY','DELIVERY','WAYBILL')),
                            truck_id varchar(255),
                            primary key (id)
);

create table if not exists trucks (
                        updated_at timestamp(6) not null,
                        brand varchar(255),
                        license_plate varchar(255) not null,
                        model varchar(255),
                        primary key (license_plate)
);

create table if not exists waste_containers (
                           uuid uuid not null,
                           id varchar(255),
                           notes varchar(255),
                           building_name varchar(255),
                           building_number varchar(255),
                           city varchar(255),
                           country varchar(255),
                           postal_code varchar(255),
                           street_name varchar(255),
                           location_company_id uuid,
                           primary key (uuid)
);

create table if not exists waybills (
                          delivery_date_time timestamp(6),
                          goods_item_id bigint unique,
                          pickup_date_time timestamp(6),
                          updated_at timestamp(6) not null,
                          carrier_party_id uuid,
                          consignee_party_id uuid,
                          consignor_party_id uuid,
                          pickup_party_id uuid,
                          uuid uuid not null,
                          delivery_location_id varchar(255) unique,
                          id varchar(255),
                          license_plate varchar(255),
                          note varchar(255),
                          pickup_location_id varchar(255) unique,
                          primary key (uuid)
);

alter table if exists goods
    add constraint FKmmq89gkjejce7jk9b3ifrq85n
        foreign key (consignee_party_id)
            references companies;

alter table if exists goods
    add constraint FK8b4xllidyrhdclt6pjqo5k5aq
        foreign key (goods_item_id)
            references goods_items;

alter table if exists goods
    add constraint FKjxo4a2n1ffa1vi323ixkm0efl
        foreign key (pickup_party_id)
            references companies;

alter table if exists transports
    add constraint FK9vtcum4wow21lygabe1baemab
        foreign key (carrier_party_id)
            references companies;

alter table if exists transports
    add constraint FKpfpjw6nu1nix3orr0vc2c2na6
        foreign key (consignor_party_id)
            references companies;

alter table if exists transports
    add constraint FKr7jo64ck7hsa4d9i2mucxlrjv
        foreign key (delivery_location_id)
            references locations;

alter table if exists transports
    add constraint FKi82vj9n4pe2k5fbgdmj8mc8tr
        foreign key (driver_id)
            references drivers;

alter table if exists transports
    add constraint FK8jrwx32tgeb6xn4e9jg5mueuj
        foreign key (goods_id)
            references goods;

alter table if exists transports
    add constraint FK163l7w977al0i5bepjq1207ne
        foreign key (pickup_location_id)
            references locations;

alter table if exists transports
    add constraint FK2lgi3xage1g6g2daa75jhnw1c
        foreign key (truck_id)
            references trucks;

alter table if exists waste_containers
    add constraint FK_waste_containers_company
        foreign key (location_company_id)
            references companies;

alter table if exists waybills
    add constraint FKexb5sdt0oqb9a6ehk1f05krmv
        foreign key (carrier_party_id)
            references companies;

alter table if exists waybills
    add constraint FKsrjknpahp89cmae80n86m0hsy
        foreign key (consignee_party_id)
            references companies;

alter table if exists waybills
    add constraint FKswgts2ytehbdal35brikeaexc
        foreign key (consignor_party_id)
            references companies;

alter table if exists waybills
    add constraint FK6wh6ln69550kuiji853lvwitl
        foreign key (delivery_location_id)
            references locations;

alter table if exists waybills
    add constraint FKhaxs4v1au4fk8sahm9map6j49
        foreign key (goods_item_id)
            references goods_items;

alter table if exists waybills
    add constraint FKh7c49u3crn1swqeoton0umk4x
        foreign key (pickup_location_id)
            references locations;

alter table if exists waybills
    add constraint FK3x2ksx5hynkablsj7k46cg1qs
        foreign key (pickup_party_id)
            references companies;