/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  assertParamExists,
  createRequestFunction,
  DUMMY_BASE_URL,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString
} from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI, COLLECTION_FORMATS, operationServerMap, type RequestArgs, RequiredError } from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import type { ApproveDeclarationResponse, Pageable, PageLmaDeclarationView, PendingApprovalsResponse } from '../models';

/**
 * AmiceControllerApi - axios parameter creator
 */
export const AmiceControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {string} declarationId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        approveDeclaration: async (declarationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'declarationId' is not null or undefined
            assertParamExists('approveDeclaration', 'declarationId', declarationId)
            const localVarPath = `/amice/declarations/{declarationId}/approve`
                .replace(`{declarationId}`, encodeURIComponent(String(declarationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {Pageable} pageable
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getDeclarations: async (pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getDeclarations', 'pageable', pageable)
            const localVarPath = `/amice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                localVarQueryParameter['pageable'] = pageable;
            }

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        hasPendingApprovals: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/amice/pending-approvals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AmiceControllerApi - functional programming interface
 */
export const AmiceControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AmiceControllerApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @param {string} declarationId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveDeclaration(declarationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApproveDeclarationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveDeclaration(declarationId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AmiceControllerApi.approveDeclaration']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {Pageable} pageable
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeclarations(pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageLmaDeclarationView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDeclarations(pageable, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AmiceControllerApi.getDeclarations']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hasPendingApprovals(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PendingApprovalsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hasPendingApprovals(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AmiceControllerApi.hasPendingApprovals']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * AmiceControllerApi - factory interface
 */
export const AmiceControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AmiceControllerApiFp(configuration)
    return {
        /**
         *
         * @param {string} declarationId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveDeclaration(declarationId: string, options?: any): AxiosPromise<ApproveDeclarationResponse> {
            return localVarFp.approveDeclaration(declarationId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {Pageable} pageable
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeclarations(pageable: Pageable, options?: any): AxiosPromise<PageLmaDeclarationView> {
            return localVarFp.getDeclarations(pageable, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hasPendingApprovals(options?: any): AxiosPromise<PendingApprovalsResponse> {
            return localVarFp.hasPendingApprovals(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AmiceControllerApi - object-oriented interface
 */
export class AmiceControllerApi extends BaseAPI {
    /**
     *
     * @param {string} declarationId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmiceControllerApi
     */
    public approveDeclaration(declarationId: string, options?: RawAxiosRequestConfig) {
        return AmiceControllerApiFp(this.configuration).approveDeclaration(declarationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {Pageable} pageable
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmiceControllerApi
     */
    public getDeclarations(pageable: Pageable, options?: RawAxiosRequestConfig) {
        return AmiceControllerApiFp(this.configuration).getDeclarations(pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmiceControllerApi
     */
    public hasPendingApprovals(options?: RawAxiosRequestConfig) {
        return AmiceControllerApiFp(this.configuration).hasPendingApprovals(options).then((request) => request(this.axios, this.basePath));
    }
}
