/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  assertParamExists,
  createRequestFunction,
  DUMMY_BASE_URL,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString
} from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI, COLLECTION_FORMATS, operationServerMap, type RequestArgs, RequiredError } from '../base';
// @ts-ignore
import type { CatalogItemResponse } from '../models';

/**
 * CatalogControllerApi - axios parameter creator
 */
export const CatalogControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {GetCatalogItemByTypeAndIdItemTypeEnum} itemType
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getCatalogItemByTypeAndId: async (itemType: GetCatalogItemByTypeAndIdItemTypeEnum, id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemType' is not null or undefined
            assertParamExists('getCatalogItemByTypeAndId', 'itemType', itemType)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCatalogItemByTypeAndId', 'id', id)
            const localVarPath = `/catalog/items/{itemType}/{id}`
                .replace(`{itemType}`, encodeURIComponent(String(itemType)))
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getMaterialById1: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMaterialById1', 'id', id)
            const localVarPath = `/catalog/materials/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getProductById1: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProductById1', 'id', id)
            const localVarPath = `/catalog/products/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} [query]
         * @param {Set<SearchCatalogItemsItemTypesEnum>} [itemTypes]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        searchCatalogItems: async (query?: string, itemTypes?: Set<SearchCatalogItemsItemTypesEnum>, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/catalog/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (itemTypes) {
                localVarQueryParameter['itemTypes'] = itemTypes;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CatalogControllerApi - functional programming interface
 */
export const CatalogControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CatalogControllerApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @param {GetCatalogItemByTypeAndIdItemTypeEnum} itemType
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCatalogItemByTypeAndId(itemType: GetCatalogItemByTypeAndIdItemTypeEnum, id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CatalogItemResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCatalogItemByTypeAndId(itemType, id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CatalogControllerApi.getCatalogItemByTypeAndId']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMaterialById1(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CatalogItemResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMaterialById1(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CatalogControllerApi.getMaterialById1']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProductById1(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CatalogItemResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProductById1(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CatalogControllerApi.getProductById1']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {string} [query]
         * @param {Set<SearchCatalogItemsItemTypesEnum>} [itemTypes]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchCatalogItems(query?: string, itemTypes?: Set<SearchCatalogItemsItemTypesEnum>, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CatalogItemResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchCatalogItems(query, itemTypes, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CatalogControllerApi.searchCatalogItems']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * CatalogControllerApi - factory interface
 */
export const CatalogControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CatalogControllerApiFp(configuration)
    return {
        /**
         *
         * @param {'MATERIAL' | 'PRODUCT'} itemType
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCatalogItemByTypeAndId(itemType: GetCatalogItemByTypeAndIdItemTypeEnum, id: number, options?: any): AxiosPromise<CatalogItemResponse> {
            return localVarFp.getCatalogItemByTypeAndId(itemType, id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMaterialById1(id: number, options?: any): AxiosPromise<CatalogItemResponse> {
            return localVarFp.getMaterialById1(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductById1(id: number, options?: any): AxiosPromise<CatalogItemResponse> {
            return localVarFp.getProductById1(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {string} [query]
         * @param {Set<'MATERIAL' | 'PRODUCT'>} [itemTypes]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchCatalogItems(query?: string, itemTypes?: Set<SearchCatalogItemsItemTypesEnum>, limit?: number, options?: any): AxiosPromise<Array<CatalogItemResponse>> {
            return localVarFp.searchCatalogItems(query, itemTypes, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CatalogControllerApi - object-oriented interface
 */
export class CatalogControllerApi extends BaseAPI {
    /**
     *
     * @param {'MATERIAL' | 'PRODUCT'} itemType
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogControllerApi
     */
    public getCatalogItemByTypeAndId(itemType: GetCatalogItemByTypeAndIdItemTypeEnum, id: number, options?: RawAxiosRequestConfig) {
        return CatalogControllerApiFp(this.configuration).getCatalogItemByTypeAndId(itemType, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogControllerApi
     */
    public getMaterialById1(id: number, options?: RawAxiosRequestConfig) {
        return CatalogControllerApiFp(this.configuration).getMaterialById1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogControllerApi
     */
    public getProductById1(id: number, options?: RawAxiosRequestConfig) {
        return CatalogControllerApiFp(this.configuration).getProductById1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {string} [query]
     * @param {Set<'MATERIAL' | 'PRODUCT'>} [itemTypes]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogControllerApi
     */
    public searchCatalogItems(query?: string, itemTypes?: Set<SearchCatalogItemsItemTypesEnum>, limit?: number, options?: RawAxiosRequestConfig) {
        return CatalogControllerApiFp(this.configuration).searchCatalogItems(query, itemTypes, limit, options).then((request) => request(this.axios, this.basePath));
    }
}
