/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MaterialGroupRequest } from '../models';
// @ts-ignore
import type { MaterialGroupResponse } from '../models';
/**
 * MaterialGroupControllerApi - axios parameter creator
 */
export const MaterialGroupControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {MaterialGroupRequest} materialGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        createMaterialGroup: async (materialGroupRequest: MaterialGroupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'materialGroupRequest' is not null or undefined
            assertParamExists('createMaterialGroup', 'materialGroupRequest', materialGroupRequest)
            const localVarPath = `/material-groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(materialGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        deleteMaterialGroup: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteMaterialGroup', 'id', id)
            const localVarPath = `/material-groups/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getAllMaterialGroups: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/material-groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getMaterialGroupById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMaterialGroupById', 'id', id)
            const localVarPath = `/material-groups/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {MaterialGroupRequest} materialGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        updateMaterialGroup: async (id: string, materialGroupRequest: MaterialGroupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateMaterialGroup', 'id', id)
            // verify required parameter 'materialGroupRequest' is not null or undefined
            assertParamExists('updateMaterialGroup', 'materialGroupRequest', materialGroupRequest)
            const localVarPath = `/material-groups/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(materialGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MaterialGroupControllerApi - functional programming interface
 */
export const MaterialGroupControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MaterialGroupControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {MaterialGroupRequest} materialGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMaterialGroup(materialGroupRequest: MaterialGroupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMaterialGroup(materialGroupRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialGroupControllerApi.createMaterialGroup']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMaterialGroup(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMaterialGroup(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialGroupControllerApi.deleteMaterialGroup']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMaterialGroups(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MaterialGroupResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMaterialGroups(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialGroupControllerApi.getAllMaterialGroups']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMaterialGroupById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMaterialGroupById(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialGroupControllerApi.getMaterialGroupById']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {MaterialGroupRequest} materialGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMaterialGroup(id: string, materialGroupRequest: MaterialGroupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMaterialGroup(id, materialGroupRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialGroupControllerApi.updateMaterialGroup']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * MaterialGroupControllerApi - factory interface
 */
export const MaterialGroupControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MaterialGroupControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {MaterialGroupRequest} materialGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMaterialGroup(materialGroupRequest: MaterialGroupRequest, options?: any): AxiosPromise<MaterialGroupResponse> {
            return localVarFp.createMaterialGroup(materialGroupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMaterialGroup(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteMaterialGroup(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMaterialGroups(options?: any): AxiosPromise<Array<MaterialGroupResponse>> {
            return localVarFp.getAllMaterialGroups(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMaterialGroupById(id: string, options?: any): AxiosPromise<MaterialGroupResponse> {
            return localVarFp.getMaterialGroupById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {MaterialGroupRequest} materialGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMaterialGroup(id: string, materialGroupRequest: MaterialGroupRequest, options?: any): AxiosPromise<MaterialGroupResponse> {
            return localVarFp.updateMaterialGroup(id, materialGroupRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MaterialGroupControllerApi - object-oriented interface
 */
export class MaterialGroupControllerApi extends BaseAPI {
    /**
     * 
     * @param {MaterialGroupRequest} materialGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialGroupControllerApi
     */
    public createMaterialGroup(materialGroupRequest: MaterialGroupRequest, options?: RawAxiosRequestConfig) {
        return MaterialGroupControllerApiFp(this.configuration).createMaterialGroup(materialGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialGroupControllerApi
     */
    public deleteMaterialGroup(id: string, options?: RawAxiosRequestConfig) {
        return MaterialGroupControllerApiFp(this.configuration).deleteMaterialGroup(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialGroupControllerApi
     */
    public getAllMaterialGroups(options?: RawAxiosRequestConfig) {
        return MaterialGroupControllerApiFp(this.configuration).getAllMaterialGroups(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialGroupControllerApi
     */
    public getMaterialGroupById(id: string, options?: RawAxiosRequestConfig) {
        return MaterialGroupControllerApiFp(this.configuration).getMaterialGroupById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {MaterialGroupRequest} materialGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialGroupControllerApi
     */
    public updateMaterialGroup(id: string, materialGroupRequest: MaterialGroupRequest, options?: RawAxiosRequestConfig) {
        return MaterialGroupControllerApiFp(this.configuration).updateMaterialGroup(id, materialGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
