/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  assertParamExists,
  createRequestFunction,
  DUMMY_BASE_URL,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString
} from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI, COLLECTION_FORMATS, operationServerMap, type RequestArgs, RequiredError } from '../base';
// @ts-ignore
// @ts-ignore
import type { MaterialPriceRequest, MaterialPriceResponse } from '../models';

/**
 * MaterialPriceControllerApi - axios parameter creator
 */
export const MaterialPriceControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {string} id
         * @param {MaterialPriceRequest} materialPriceRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        createMaterialPrice: async (id: string, materialPriceRequest: MaterialPriceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createMaterialPrice', 'id', id)
            // verify required parameter 'materialPriceRequest' is not null or undefined
            assertParamExists('createMaterialPrice', 'materialPriceRequest', materialPriceRequest)
            const localVarPath = `/material-prices/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(materialPriceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        deleteMaterialPrice: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteMaterialPrice', 'id', id)
            const localVarPath = `/material-prices/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getAllMaterialsWithPrices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/material-prices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getMaterialPrice: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMaterialPrice', 'id', id)
            const localVarPath = `/material-prices/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {MaterialPriceRequest} materialPriceRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        updateMaterialPrice: async (id: string, materialPriceRequest: MaterialPriceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateMaterialPrice', 'id', id)
            // verify required parameter 'materialPriceRequest' is not null or undefined
            assertParamExists('updateMaterialPrice', 'materialPriceRequest', materialPriceRequest)
            const localVarPath = `/material-prices/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(materialPriceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MaterialPriceControllerApi - functional programming interface
 */
export const MaterialPriceControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MaterialPriceControllerApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @param {string} id
         * @param {MaterialPriceRequest} materialPriceRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMaterialPrice(id: string, materialPriceRequest: MaterialPriceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialPriceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMaterialPrice(id, materialPriceRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialPriceControllerApi.createMaterialPrice']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMaterialPrice(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMaterialPrice(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialPriceControllerApi.deleteMaterialPrice']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMaterialsWithPrices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MaterialPriceResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMaterialsWithPrices(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialPriceControllerApi.getAllMaterialsWithPrices']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMaterialPrice(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialPriceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMaterialPrice(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialPriceControllerApi.getMaterialPrice']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {MaterialPriceRequest} materialPriceRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMaterialPrice(id: string, materialPriceRequest: MaterialPriceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialPriceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMaterialPrice(id, materialPriceRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialPriceControllerApi.updateMaterialPrice']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * MaterialPriceControllerApi - factory interface
 */
export const MaterialPriceControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MaterialPriceControllerApiFp(configuration)
    return {
        /**
         *
         * @param {string} id
         * @param {MaterialPriceRequest} materialPriceRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMaterialPrice(id: string, materialPriceRequest: MaterialPriceRequest, options?: any): AxiosPromise<MaterialPriceResponse> {
            return localVarFp.createMaterialPrice(id, materialPriceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMaterialPrice(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteMaterialPrice(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMaterialsWithPrices(options?: any): AxiosPromise<Array<MaterialPriceResponse>> {
            return localVarFp.getAllMaterialsWithPrices(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMaterialPrice(id: string, options?: any): AxiosPromise<MaterialPriceResponse> {
            return localVarFp.getMaterialPrice(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {string} id
         * @param {MaterialPriceRequest} materialPriceRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMaterialPrice(id: string, materialPriceRequest: MaterialPriceRequest, options?: any): AxiosPromise<MaterialPriceResponse> {
            return localVarFp.updateMaterialPrice(id, materialPriceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MaterialPriceControllerApi - object-oriented interface
 */
export class MaterialPriceControllerApi extends BaseAPI {
    /**
     *
     * @param {string} id
     * @param {MaterialPriceRequest} materialPriceRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialPriceControllerApi
     */
    public createMaterialPrice(id: string, materialPriceRequest: MaterialPriceRequest, options?: RawAxiosRequestConfig) {
        return MaterialPriceControllerApiFp(this.configuration).createMaterialPrice(id, materialPriceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialPriceControllerApi
     */
    public deleteMaterialPrice(id: string, options?: RawAxiosRequestConfig) {
        return MaterialPriceControllerApiFp(this.configuration).deleteMaterialPrice(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialPriceControllerApi
     */
    public getAllMaterialsWithPrices(options?: RawAxiosRequestConfig) {
        return MaterialPriceControllerApiFp(this.configuration).getAllMaterialsWithPrices(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialPriceControllerApi
     */
    public getMaterialPrice(id: string, options?: RawAxiosRequestConfig) {
        return MaterialPriceControllerApiFp(this.configuration).getMaterialPrice(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {string} id
     * @param {MaterialPriceRequest} materialPriceRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialPriceControllerApi
     */
    public updateMaterialPrice(id: string, materialPriceRequest: MaterialPriceRequest, options?: RawAxiosRequestConfig) {
        return MaterialPriceControllerApiFp(this.configuration).updateMaterialPrice(id, materialPriceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
