/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  assertParamExists,
  createRequestFunction,
  DUMMY_BASE_URL,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString
} from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI, COLLECTION_FORMATS, operationServerMap, type RequestArgs, RequiredError } from '../base';
// @ts-ignore
// @ts-ignore
import type { MaterialRequest, MaterialResponse } from '../models';

/**
 * MaterialControllerApi - axios parameter creator
 */
export const MaterialControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {MaterialRequest} materialRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        createMaterial: async (materialRequest: MaterialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'materialRequest' is not null or undefined
            assertParamExists('createMaterial', 'materialRequest', materialRequest)
            const localVarPath = `/materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(materialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        deleteMaterial: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteMaterial', 'id', id)
            const localVarPath = `/materials/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getAllMaterials: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getMaterialById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMaterialById', 'id', id)
            const localVarPath = `/materials/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {number} id
         * @param {MaterialRequest} materialRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        updateMaterial: async (id: number, materialRequest: MaterialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateMaterial', 'id', id)
            // verify required parameter 'materialRequest' is not null or undefined
            assertParamExists('updateMaterial', 'materialRequest', materialRequest)
            const localVarPath = `/materials/{id}`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(materialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MaterialControllerApi - functional programming interface
 */
export const MaterialControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MaterialControllerApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @param {MaterialRequest} materialRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMaterial(materialRequest: MaterialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMaterial(materialRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialControllerApi.createMaterial']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMaterial(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMaterial(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialControllerApi.deleteMaterial']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMaterials(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MaterialResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMaterials(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialControllerApi.getAllMaterials']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMaterialById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMaterialById(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialControllerApi.getMaterialById']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @param {number} id
         * @param {MaterialRequest} materialRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMaterial(id: number, materialRequest: MaterialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaterialResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMaterial(id, materialRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MaterialControllerApi.updateMaterial']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * MaterialControllerApi - factory interface
 */
export const MaterialControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MaterialControllerApiFp(configuration)
    return {
        /**
         *
         * @param {MaterialRequest} materialRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMaterial(materialRequest: MaterialRequest, options?: any): AxiosPromise<MaterialResponse> {
            return localVarFp.createMaterial(materialRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMaterial(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteMaterial(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMaterials(options?: any): AxiosPromise<Array<MaterialResponse>> {
            return localVarFp.getAllMaterials(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMaterialById(id: number, options?: any): AxiosPromise<MaterialResponse> {
            return localVarFp.getMaterialById(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {number} id
         * @param {MaterialRequest} materialRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMaterial(id: number, materialRequest: MaterialRequest, options?: any): AxiosPromise<MaterialResponse> {
            return localVarFp.updateMaterial(id, materialRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MaterialControllerApi - object-oriented interface
 */
export class MaterialControllerApi extends BaseAPI {
    /**
     *
     * @param {MaterialRequest} materialRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialControllerApi
     */
    public createMaterial(materialRequest: MaterialRequest, options?: RawAxiosRequestConfig) {
        return MaterialControllerApiFp(this.configuration).createMaterial(materialRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialControllerApi
     */
    public deleteMaterial(id: number, options?: RawAxiosRequestConfig) {
        return MaterialControllerApiFp(this.configuration).deleteMaterial(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialControllerApi
     */
    public getAllMaterials(options?: RawAxiosRequestConfig) {
        return MaterialControllerApiFp(this.configuration).getAllMaterials(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialControllerApi
     */
    public getMaterialById(id: number, options?: RawAxiosRequestConfig) {
        return MaterialControllerApiFp(this.configuration).getMaterialById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {number} id
     * @param {MaterialRequest} materialRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MaterialControllerApi
     */
    public updateMaterial(id: number, materialRequest: MaterialRequest, options?: RawAxiosRequestConfig) {
        return MaterialControllerApiFp(this.configuration).updateMaterial(id, materialRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
