/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateSignatureRequest } from '../models';
// @ts-ignore
import type { SignatureStatusView } from '../models';
/**
 * SignatureControllerApi - axios parameter creator
 */
export const SignatureControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getSignatureStatuses: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSignatureStatuses', 'id', id)
            const localVarPath = `/transport/{id}/waybill/signature-status`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {CreateSignatureRequest} createSignatureRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        saveSignature: async (id: string, createSignatureRequest: CreateSignatureRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('saveSignature', 'id', id)
            // verify required parameter 'createSignatureRequest' is not null or undefined
            assertParamExists('saveSignature', 'createSignatureRequest', createSignatureRequest)
            const localVarPath = `/transport/{id}/waybill/signature`
                .replace(`{id}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSignatureRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SignatureControllerApi - functional programming interface
 */
export const SignatureControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SignatureControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSignatureStatuses(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignatureStatusView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSignatureStatuses(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SignatureControllerApi.getSignatureStatuses']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {CreateSignatureRequest} createSignatureRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveSignature(id: string, createSignatureRequest: CreateSignatureRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignatureStatusView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveSignature(id, createSignatureRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SignatureControllerApi.saveSignature']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * SignatureControllerApi - factory interface
 */
export const SignatureControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SignatureControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSignatureStatuses(id: string, options?: any): AxiosPromise<SignatureStatusView> {
            return localVarFp.getSignatureStatuses(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {CreateSignatureRequest} createSignatureRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSignature(id: string, createSignatureRequest: CreateSignatureRequest, options?: any): AxiosPromise<SignatureStatusView> {
            return localVarFp.saveSignature(id, createSignatureRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SignatureControllerApi - object-oriented interface
 */
export class SignatureControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignatureControllerApi
     */
    public getSignatureStatuses(id: string, options?: RawAxiosRequestConfig) {
        return SignatureControllerApiFp(this.configuration).getSignatureStatuses(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {CreateSignatureRequest} createSignatureRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignatureControllerApi
     */
    public saveSignature(id: string, createSignatureRequest: CreateSignatureRequest, options?: RawAxiosRequestConfig) {
        return SignatureControllerApiFp(this.configuration).saveSignature(id, createSignatureRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
