/* tslint:disable */
/* eslint-disable */
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateWasteTransportResponse } from '../models';
// @ts-ignore
import type { UpdateWasteTransportResponse } from '../models';
// @ts-ignore
import type { WasteTransportRequest } from '../models';
/**
 * WasteTransportControllerApi - axios parameter creator
 * @export
 */
export const WasteTransportControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WasteTransportRequest} wasteTransportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWasteTransport: async (wasteTransportRequest: WasteTransportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wasteTransportRequest' is not null or undefined
            assertParamExists('createWasteTransport', 'wasteTransportRequest', wasteTransportRequest)
            const localVarPath = `/transport/waste`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wasteTransportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {WasteTransportRequest} wasteTransportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWasteTransport: async (id: string, wasteTransportRequest: WasteTransportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateWasteTransport', 'id', id)
            // verify required parameter 'wasteTransportRequest' is not null or undefined
            assertParamExists('updateWasteTransport', 'wasteTransportRequest', wasteTransportRequest)
            const localVarPath = `/transport/waste/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wasteTransportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WasteTransportControllerApi - functional programming interface
 * @export
 */
export const WasteTransportControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WasteTransportControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {WasteTransportRequest} wasteTransportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWasteTransport(wasteTransportRequest: WasteTransportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateWasteTransportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWasteTransport(wasteTransportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WasteTransportControllerApi.createWasteTransport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {WasteTransportRequest} wasteTransportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateWasteTransport(id: string, wasteTransportRequest: WasteTransportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateWasteTransportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateWasteTransport(id, wasteTransportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WasteTransportControllerApi.updateWasteTransport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WasteTransportControllerApi - factory interface
 * @export
 */
export const WasteTransportControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WasteTransportControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {WasteTransportRequest} wasteTransportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWasteTransport(wasteTransportRequest: WasteTransportRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateWasteTransportResponse> {
            return localVarFp.createWasteTransport(wasteTransportRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {WasteTransportRequest} wasteTransportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWasteTransport(id: string, wasteTransportRequest: WasteTransportRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateWasteTransportResponse> {
            return localVarFp.updateWasteTransport(id, wasteTransportRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WasteTransportControllerApi - object-oriented interface
 * @export
 * @class WasteTransportControllerApi
 * @extends {BaseAPI}
 */
export class WasteTransportControllerApi extends BaseAPI {
    /**
     * 
     * @param {WasteTransportRequest} wasteTransportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WasteTransportControllerApi
     */
    public createWasteTransport(wasteTransportRequest: WasteTransportRequest, options?: RawAxiosRequestConfig) {
        return WasteTransportControllerApiFp(this.configuration).createWasteTransport(wasteTransportRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {WasteTransportRequest} wasteTransportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WasteTransportControllerApi
     */
    public updateWasteTransport(id: string, wasteTransportRequest: WasteTransportRequest, options?: RawAxiosRequestConfig) {
        return WasteTransportControllerApiFp(this.configuration).updateWasteTransport(id, wasteTransportRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

