/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { WasteStreamDto } from '../models';
/**
 * WasteStreamControllerApi - axios parameter creator
 * @export
 */
export const WasteStreamControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WasteStreamDto} wasteStreamDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWasteStream: async (wasteStreamDto: WasteStreamDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wasteStreamDto' is not null or undefined
            assertParamExists('createWasteStream', 'wasteStreamDto', wasteStreamDto)
            const localVarPath = `/waste-streams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wasteStreamDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} number 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWasteStream: async (number: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'number' is not null or undefined
            assertParamExists('deleteWasteStream', 'number', number)
            const localVarPath = `/waste-streams/{number}`
                .replace(`{${"number"}}`, encodeURIComponent(String(number)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWasteStreams: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/waste-streams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} number 
         * @param {WasteStreamDto} wasteStreamDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWasteStream: async (number: string, wasteStreamDto: WasteStreamDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'number' is not null or undefined
            assertParamExists('updateWasteStream', 'number', number)
            // verify required parameter 'wasteStreamDto' is not null or undefined
            assertParamExists('updateWasteStream', 'wasteStreamDto', wasteStreamDto)
            const localVarPath = `/waste-streams/{number}`
                .replace(`{${"number"}}`, encodeURIComponent(String(number)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wasteStreamDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WasteStreamControllerApi - functional programming interface
 * @export
 */
export const WasteStreamControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WasteStreamControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {WasteStreamDto} wasteStreamDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWasteStream(wasteStreamDto: WasteStreamDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WasteStreamDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWasteStream(wasteStreamDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WasteStreamControllerApi.createWasteStream']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} number 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWasteStream(number: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWasteStream(number, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WasteStreamControllerApi.deleteWasteStream']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWasteStreams(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WasteStreamDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWasteStreams(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WasteStreamControllerApi.getWasteStreams']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} number 
         * @param {WasteStreamDto} wasteStreamDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateWasteStream(number: string, wasteStreamDto: WasteStreamDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WasteStreamDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateWasteStream(number, wasteStreamDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WasteStreamControllerApi.updateWasteStream']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WasteStreamControllerApi - factory interface
 * @export
 */
export const WasteStreamControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WasteStreamControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {WasteStreamDto} wasteStreamDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWasteStream(wasteStreamDto: WasteStreamDto, options?: RawAxiosRequestConfig): AxiosPromise<WasteStreamDto> {
            return localVarFp.createWasteStream(wasteStreamDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} number 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWasteStream(number: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteWasteStream(number, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWasteStreams(options?: RawAxiosRequestConfig): AxiosPromise<Array<WasteStreamDto>> {
            return localVarFp.getWasteStreams(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} number 
         * @param {WasteStreamDto} wasteStreamDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWasteStream(number: string, wasteStreamDto: WasteStreamDto, options?: RawAxiosRequestConfig): AxiosPromise<WasteStreamDto> {
            return localVarFp.updateWasteStream(number, wasteStreamDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WasteStreamControllerApi - object-oriented interface
 * @export
 * @class WasteStreamControllerApi
 * @extends {BaseAPI}
 */
export class WasteStreamControllerApi extends BaseAPI {
    /**
     * 
     * @param {WasteStreamDto} wasteStreamDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WasteStreamControllerApi
     */
    public createWasteStream(wasteStreamDto: WasteStreamDto, options?: RawAxiosRequestConfig) {
        return WasteStreamControllerApiFp(this.configuration).createWasteStream(wasteStreamDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} number 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WasteStreamControllerApi
     */
    public deleteWasteStream(number: string, options?: RawAxiosRequestConfig) {
        return WasteStreamControllerApiFp(this.configuration).deleteWasteStream(number, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WasteStreamControllerApi
     */
    public getWasteStreams(options?: RawAxiosRequestConfig) {
        return WasteStreamControllerApiFp(this.configuration).getWasteStreams(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} number 
     * @param {WasteStreamDto} wasteStreamDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WasteStreamControllerApi
     */
    public updateWasteStream(number: string, wasteStreamDto: WasteStreamDto, options?: RawAxiosRequestConfig) {
        return WasteStreamControllerApiFp(this.configuration).updateWasteStream(number, wasteStreamDto, options).then((request) => request(this.axios, this.basePath));
    }
}

