/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateWeightTicketRequest } from '../models';
// @ts-ignore
import type { CreateWeightTicketResponse } from '../models';
// @ts-ignore
import type { WeightTicketListView } from '../models';
/**
 * WeightTicketControllerApi - axios parameter creator
 * @export
 */
export const WeightTicketControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateWeightTicketRequest} createWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createWeightTicketRequest: CreateWeightTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createWeightTicketRequest' is not null or undefined
            assertParamExists('create', 'createWeightTicketRequest', createWeightTicketRequest)
            const localVarPath = `/weight-tickets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWeightTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete1: async (weightTicketId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketId' is not null or undefined
            assertParamExists('delete1', 'weightTicketId', weightTicketId)
            const localVarPath = `/weight-tickets/{weightTicketId}`
                .replace(`{${"weightTicketId"}}`, encodeURIComponent(String(weightTicketId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeightTickets: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/weight-tickets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeightTicketControllerApi - functional programming interface
 * @export
 */
export const WeightTicketControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeightTicketControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateWeightTicketRequest} createWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createWeightTicketRequest: CreateWeightTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateWeightTicketResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createWeightTicketRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeightTicketControllerApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delete1(weightTicketId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delete1(weightTicketId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeightTicketControllerApi.delete1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeightTickets(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WeightTicketListView>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeightTickets(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeightTicketControllerApi.getWeightTickets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WeightTicketControllerApi - factory interface
 * @export
 */
export const WeightTicketControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeightTicketControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateWeightTicketRequest} createWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(createWeightTicketRequest: CreateWeightTicketRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateWeightTicketResponse> {
            return localVarFp.create(createWeightTicketRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete1(weightTicketId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.delete1(weightTicketId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeightTickets(options?: RawAxiosRequestConfig): AxiosPromise<Array<WeightTicketListView>> {
            return localVarFp.getWeightTickets(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WeightTicketControllerApi - object-oriented interface
 * @export
 * @class WeightTicketControllerApi
 * @extends {BaseAPI}
 */
export class WeightTicketControllerApi extends BaseAPI {
    /**
     * 
     * @param {CreateWeightTicketRequest} createWeightTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public create(createWeightTicketRequest: CreateWeightTicketRequest, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).create(createWeightTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public delete1(weightTicketId: number, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).delete1(weightTicketId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public getWeightTickets(options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).getWeightTickets(options).then((request) => request(this.axios, this.basePath));
    }
}

