/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Eazy Recycling Backend Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CancelWeightTicketRequest } from '../models';
// @ts-ignore
import type { CopyWeightTicketResponse } from '../models';
// @ts-ignore
import type { CreateInvoiceFromWeightTicketResult } from '../models';
// @ts-ignore
import type { CreateWeightTicketResponse } from '../models';
// @ts-ignore
import type { SplitWeightTicketRequest } from '../models';
// @ts-ignore
import type { SplitWeightTicketResponse } from '../models';
// @ts-ignore
import type { WeightTicketDetailView } from '../models';
// @ts-ignore
import type { WeightTicketListView } from '../models';
// @ts-ignore
import type { WeightTicketRequest } from '../models';
/**
 * WeightTicketControllerApi - axios parameter creator
 */
export const WeightTicketControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {CancelWeightTicketRequest} cancelWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        cancel: async (weightTicketNumber: number, cancelWeightTicketRequest: CancelWeightTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('cancel', 'weightTicketNumber', weightTicketNumber)
            // verify required parameter 'cancelWeightTicketRequest' is not null or undefined
            assertParamExists('cancel', 'cancelWeightTicketRequest', cancelWeightTicketRequest)
            const localVarPath = `/weight-tickets/{weightTicketNumber}/cancel`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelWeightTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        complete: async (weightTicketNumber: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('complete', 'weightTicketNumber', weightTicketNumber)
            const localVarPath = `/weight-tickets/{weightTicketNumber}/complete`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        copy: async (weightTicketNumber: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('copy', 'weightTicketNumber', weightTicketNumber)
            const localVarPath = `/weight-tickets/{weightTicketNumber}/copy`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        create: async (weightTicketRequest: WeightTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketRequest' is not null or undefined
            assertParamExists('create', 'weightTicketRequest', weightTicketRequest)
            const localVarPath = `/weight-tickets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(weightTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        createCompleted: async (weightTicketRequest: WeightTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketRequest' is not null or undefined
            assertParamExists('createCompleted', 'weightTicketRequest', weightTicketRequest)
            const localVarPath = `/weight-tickets/completed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(weightTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        createInvoice: async (weightTicketNumber: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('createInvoice', 'weightTicketNumber', weightTicketNumber)
            const localVarPath = `/weight-tickets/{weightTicketNumber}/invoice`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getWeightTicketByNumber: async (weightTicketNumber: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('getWeightTicketByNumber', 'weightTicketNumber', weightTicketNumber)
            const localVarPath = `/weight-tickets/{weightTicketNumber}`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        getWeightTickets: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/weight-tickets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {SplitWeightTicketRequest} splitWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        split: async (weightTicketNumber: number, splitWeightTicketRequest: SplitWeightTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('split', 'weightTicketNumber', weightTicketNumber)
            // verify required parameter 'splitWeightTicketRequest' is not null or undefined
            assertParamExists('split', 'splitWeightTicketRequest', splitWeightTicketRequest)
            const localVarPath = `/weight-tickets/{weightTicketNumber}/split`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(splitWeightTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}}
         */
        update: async (weightTicketNumber: number, weightTicketRequest: WeightTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightTicketNumber' is not null or undefined
            assertParamExists('update', 'weightTicketNumber', weightTicketNumber)
            // verify required parameter 'weightTicketRequest' is not null or undefined
            assertParamExists('update', 'weightTicketRequest', weightTicketRequest)
            const localVarPath = `/weight-tickets/{weightTicketNumber}`
                .replace(`{weightTicketNumber}`, encodeURIComponent(String(weightTicketNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(weightTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeightTicketControllerApi - functional programming interface
 */
export const WeightTicketControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeightTicketControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {CancelWeightTicketRequest} cancelWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancel(weightTicketNumber: number, cancelWeightTicketRequest: CancelWeightTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancel(weightTicketNumber, cancelWeightTicketRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.cancel']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async complete(weightTicketNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.complete(weightTicketNumber, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.complete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async copy(weightTicketNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CopyWeightTicketResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.copy(weightTicketNumber, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.copy']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(weightTicketRequest: WeightTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateWeightTicketResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(weightTicketRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.create']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCompleted(weightTicketRequest: WeightTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateWeightTicketResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCompleted(weightTicketRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.createCompleted']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createInvoice(weightTicketNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateInvoiceFromWeightTicketResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createInvoice(weightTicketNumber, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.createInvoice']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeightTicketByNumber(weightTicketNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WeightTicketDetailView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeightTicketByNumber(weightTicketNumber, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.getWeightTicketByNumber']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeightTickets(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WeightTicketListView>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeightTickets(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.getWeightTickets']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {SplitWeightTicketRequest} splitWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async split(weightTicketNumber: number, splitWeightTicketRequest: SplitWeightTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SplitWeightTicketResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.split(weightTicketNumber, splitWeightTicketRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.split']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(weightTicketNumber: number, weightTicketRequest: WeightTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(weightTicketNumber, weightTicketRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WeightTicketControllerApi.update']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};

/**
 * WeightTicketControllerApi - factory interface
 */
export const WeightTicketControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeightTicketControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {CancelWeightTicketRequest} cancelWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancel(weightTicketNumber: number, cancelWeightTicketRequest: CancelWeightTicketRequest, options?: any): AxiosPromise<void> {
            return localVarFp.cancel(weightTicketNumber, cancelWeightTicketRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        complete(weightTicketNumber: number, options?: any): AxiosPromise<void> {
            return localVarFp.complete(weightTicketNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copy(weightTicketNumber: number, options?: any): AxiosPromise<CopyWeightTicketResponse> {
            return localVarFp.copy(weightTicketNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(weightTicketRequest: WeightTicketRequest, options?: any): AxiosPromise<CreateWeightTicketResponse> {
            return localVarFp.create(weightTicketRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCompleted(weightTicketRequest: WeightTicketRequest, options?: any): AxiosPromise<CreateWeightTicketResponse> {
            return localVarFp.createCompleted(weightTicketRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInvoice(weightTicketNumber: number, options?: any): AxiosPromise<CreateInvoiceFromWeightTicketResult> {
            return localVarFp.createInvoice(weightTicketNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeightTicketByNumber(weightTicketNumber: number, options?: any): AxiosPromise<WeightTicketDetailView> {
            return localVarFp.getWeightTicketByNumber(weightTicketNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeightTickets(options?: any): AxiosPromise<Array<WeightTicketListView>> {
            return localVarFp.getWeightTickets(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {SplitWeightTicketRequest} splitWeightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        split(weightTicketNumber: number, splitWeightTicketRequest: SplitWeightTicketRequest, options?: any): AxiosPromise<SplitWeightTicketResponse> {
            return localVarFp.split(weightTicketNumber, splitWeightTicketRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} weightTicketNumber 
         * @param {WeightTicketRequest} weightTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(weightTicketNumber: number, weightTicketRequest: WeightTicketRequest, options?: any): AxiosPromise<void> {
            return localVarFp.update(weightTicketNumber, weightTicketRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WeightTicketControllerApi - object-oriented interface
 */
export class WeightTicketControllerApi extends BaseAPI {
    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {CancelWeightTicketRequest} cancelWeightTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public cancel(weightTicketNumber: number, cancelWeightTicketRequest: CancelWeightTicketRequest, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).cancel(weightTicketNumber, cancelWeightTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public complete(weightTicketNumber: number, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).complete(weightTicketNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public copy(weightTicketNumber: number, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).copy(weightTicketNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WeightTicketRequest} weightTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public create(weightTicketRequest: WeightTicketRequest, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).create(weightTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WeightTicketRequest} weightTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public createCompleted(weightTicketRequest: WeightTicketRequest, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).createCompleted(weightTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public createInvoice(weightTicketNumber: number, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).createInvoice(weightTicketNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public getWeightTicketByNumber(weightTicketNumber: number, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).getWeightTicketByNumber(weightTicketNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public getWeightTickets(options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).getWeightTickets(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {SplitWeightTicketRequest} splitWeightTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public split(weightTicketNumber: number, splitWeightTicketRequest: SplitWeightTicketRequest, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).split(weightTicketNumber, splitWeightTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} weightTicketNumber 
     * @param {WeightTicketRequest} weightTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightTicketControllerApi
     */
    public update(weightTicketNumber: number, weightTicketRequest: WeightTicketRequest, options?: RawAxiosRequestConfig) {
        return WeightTicketControllerApiFp(this.configuration).update(weightTicketNumber, weightTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
