create table if not exists companies (
                           updated_at timestamp(6),
                           id uuid not null,
                           building_name varchar(255),
                           building_number varchar(255),
                           chamber_of_commerce_id varchar(255) unique,
                           city varchar(255),
                           country varchar(255),
                           name varchar(255),
                           postal_code varchar(255),
                           street_name varchar(255),
                           processor_id text,
                           vihb_id varchar(255) unique,
                           primary key (id)
);

create table if not exists company_branches (
                         id uuid not null,
                         company_id uuid not null,
                         street_name text not null,
                         postal_code text not null,
                         city text not null,
                         updated_at timestamp(6),
                         building_name text,
                         building_number text not null,
                         country text
);


create table if not exists drivers (
                         updated_at timestamp(6) not null,
                         id uuid not null,
                         first_name varchar(255) not null,
                         last_name varchar(255) not null,
                         primary key (id)
);

create table if not exists goods (
                       goods_item_id bigint unique,
                       updated_at timestamp(6) not null,
                       consignor_classification smallint,
                       consignee_party_id uuid,
                       pickup_party_id uuid,
                       uuid uuid not null,
                       id varchar(255),
                       note varchar(255),
                       primary key (uuid)
);

create table if not exists goods_items (
                             net_net_weight integer not null,
                             quantity integer not null,
                             id bigint generated by default as identity,
                             container_number varchar(255),
                             eural_code varchar(255),
                             name varchar(255),
                             unit varchar(255),
                             waste_stream_number varchar(255),
                             processing_method_code text,
                             primary key (id)
);

create table if not exists locations (
                           building_name varchar(255),
                           building_number varchar(255),
                           city varchar(255),
                           country varchar(255),
                           description varchar(255),
                           id varchar(255) not null,
                           location_type_code varchar(255),
                           postal_code varchar(255),
                           street_name varchar(255),
                           primary key (id)
);

create table if not exists transports (
                          delivery_date_time timestamp(6) without time zone,
                          pickup_date_time timestamp(6) without time zone,
                          updated_at timestamp(6) without time zone NOT NULL,
                          carrier_party_id uuid,
                          consignor_party_id uuid,
                          driver_id uuid,
                          goods_id uuid,
                          id uuid NOT NULL,
                          delivery_location_id character varying(255),
                          pickup_location_id character varying(255),
                          transport_type text,
                          truck_id character varying(255),
                          display_number text,
                          container_id uuid,
                          delivery_company_id uuid,
                          delivery_company_branch_id uuid,
                          pickup_company_id uuid,
                          pickup_company_branch_id uuid,
                          note text,
                          container_operation text CHECK (container_operation IN ('EXCHANGE', 'EMPTY', 'PICKUP', 'DELIVERY', 'WAYBILL')),
                          sequence_number integer,
                          transport_hours NUMERIC(3,1)
);

create table if not exists trucks (
                        updated_at timestamp(6) not null,
                        brand varchar(255),
                        license_plate varchar(255) not null,
                        model varchar(255),
                        primary key (license_plate)
);

create table if not exists waste_containers (
                           uuid uuid not null,
                           id varchar(255),
                           notes varchar(255),
                           building_name varchar(255),
                           building_number varchar(255),
                           city varchar(255),
                           country varchar(255),
                           postal_code varchar(255),
                           street_name varchar(255),
                           location_company_id uuid,
                           primary key (uuid)
);

create table if not exists waybills (
                          delivery_date_time timestamp(6),
                          goods_item_id bigint unique,
                          pickup_date_time timestamp(6),
                          updated_at timestamp(6) not null,
                          carrier_party_id uuid,
                          consignee_party_id uuid,
                          consignor_party_id uuid,
                          pickup_party_id uuid,
                          uuid uuid not null,
                          delivery_location_id varchar(255) unique,
                          id varchar(255),
                          license_plate varchar(255),
                          note varchar(255),
                          pickup_location_id varchar(255) unique,
                          primary key (uuid)
);

create table if not exists profiles (
                           id uuid not null,
                           first_name text not null,
                           last_name text not null
);

create table if not exists container_operations_log (
                          updated_at timestamp(6) not null,
                          id uuid not null,
                          created_at timestamp(6) not null,
                          transport_type text,
                          truck_id character varying(255),
                          display_number text,
                          container_id uuid,
                          delivery_company_id uuid,
                          pickup_company_id uuid,
                          note text,
                          container_operation text CHECK (container_operation IN ('EXCHANGE', 'EMPTY', 'PICKUP', 'DELIVERY', 'WAYBILL'))
);

create table if not exists signatures (
                                       transport_id uuid not null,
                                       consignor_signature text,
                                       consignor_email text,
                                       consignor_signed_at timestamp with time zone,
                                       pickup_signature text,
                                       pickup_email text,
                                       pickup_signed_at timestamp with time zone,
                                       carrier_signature text,
                                       carrier_email text,
                                       carrier_signed_at timestamp with time zone,
                                       consignee_signature text,
                                       consignee_email text,
                                       consignee_signed_at timestamp with time zone
);

create table if not exists eural (
                                  code text not null,
                                  description text not null
);

create table if not exists processing_methods (
                                  code text not null,
                                  description text not null
);

create table if not exists waste_streams (
                                  number text not null,
                                  name text not null,
                                  eural_code text not null,
                                  processing_method_code text not null,
                                  waste_collection_type text not null,
                                  pickup_location_id text,
                                  consignor_party_id uuid not null,
                                  pickup_party_id uuid not null,
                                  dealer_party_id uuid,
                                  collector_party_id uuid,
                                  broker_party_id uuid,
                                  processor_party_id text,
                                  status text,
                                  last_activity_at timestamp with time zone not null default now()
);


create table if not exists pickup_locations (
                                 id text not null,
                                 created_at timestamp with time zone not null default now(),
                                 location_type text not null,
                                 street_name text,
                                 building_number text,
                                 building_number_addition text,
                                 country text,
                                 proximity_description text,
                                 city text,
                                 postal_code text,
                                 company_id uuid
);

create sequence if not exists weight_tickets_id_seq start with 1 increment by 1;

create table if not exists weight_tickets (
                                 id bigint not null,
                                 consignor_party_id uuid not null,
                                 carrier_party_id uuid,
                                 truck_license_plate varchar(255),
                                 reclamation varchar(255),
                                 note varchar(255),
                                 status varchar(50) not null,
                                 created_at timestamp(6) not null,
                                 updated_at timestamp(6),
                                 weighted_at timestamp(6),
                                 primary key (id)
);
